### ISSUE TITLE
tab close buttons doesn't appear

### ISSUE THREAD

**Issue by fotonmoton** [Croydon/vertical-tabs-reloaded#100]
Add-on version: 0.8.3.1
Firefox version: 53.0.3
OS + OS-Version: Mac OS 10.11.5
Other tab + user interface related add-ons: suspend tab

Tab close button is not visible but I still can close tabs.
<img width="476" alt="image" src="https://user-images.githubusercontent.com/7763084/27002599-8d52db56-4dee-11e7-93b6-f3ab15c7e487.png">
<img width="359" alt="image" src="https://user-images.githubusercontent.com/7763084/27002618-e7496cba-4dee-11e7-8deb-b814c8246851.png">

**Comment by Croydon** [comment]
@fotonmoton Can you still reproduce this?
And what Firefox theme do you use?

**Comment by fotonmoton** [comment]
@Croydon currently not on mac, theme - Compact Dark.

**Comment by Croydon** [comment]
Alright. If this bug should appear again please report it :)
