### ISSUE TITLE
when new browser window opens up,  the vertical tabs width is not persistant

### ISSUE THREAD

**Issue by jonasflint** [Croydon/vertical-tabs-reloaded#103]
Add-on version: 0.8.3.1
Firefox version: 54
OS + OS-Version: Mac OS Sierra v 10.12.5
Other tab + user interface related add-ons: Tab Mix Plus

When opening a new window, the vertical tab opens up wide instead of maintaining the narrow state.  (I resize it to the favicon) 

Example: http://d.pr/i/696uT7

want it to stay like this: http://d.pr/i/Opx7g7

this also happens when you take a tab out another window.  The tab bar comes out wide again...

**Comment by Croydon** [comment]
I'm not going to fix this in the current legacy form of the add-on.

When VTR is rewritten as a WebExtension the compact mode in the current form will go away. More information at #135.
