### ISSUE TITLE
Use Firefox theme for tab sidebar

### ISSUE THREAD

**Issue by mrowwy** [Croydon/vertical-tabs-reloaded#104]
Would it be possible to have a theme mode that uses the installed theme to color the vertical tab bar with the same/similar colors as a theme would instead of the predefined methods in the vertical-tabs-reloaded menu. I think this would make it a bit more easy-on-the-eyes.

Otherwise, great work! :)

Add-on version: 0.8.3.1
Firefox version: 54.0.1
OS + OS-Version: W10
Other tab + user interface related add-ons:

**Comment by Croydon** [comment]
Right now there is the "None / Firefox defaults" theme option, it leaves the style choices mostly to third parties. It is not perfect, but it works. Unfortunately, this feature is likely to go away, since WebExtensions are strongly isolated from Firefox and each other. More information at #13.
