### ISSUE TITLE
'New tab' option missing from tabbar

### ISSUE THREAD

**Issue by ludasmokva** [Croydon/vertical-tabs-reloaded#108]
Add-on version: 0.8.3.1
Firefox version: 54.0.1
OS + OS-Version: Win 7
Other tab + user interface related add-ons: Tab Mix Plus

The little '+' icon next to the menu triangle on the tabbar has disappeared. So now in order to open a new tab, I have to right click somewhere on the empty space and choose 'open new tab'. 
I recently installed Tab Mix Plus (within last few days). 
I can't say for certain if the two issues are related as I only noticed it today. But it seems likely. There is an option in Tab Mix Plus to show new tab button on the tab bar (Display > Tab bar), and although I am not sure if this is what it refers to, it is ticked.
I don't know if this is a bug, or expected. Nor do I know if it can be adjusted somewhere in the settings. Although certainly not urgent - the extra step is not life shattering - I do have to say it is a bit annoying and I miss it. 
It's a shame, as the only reason I even installed the Tab Mix Plus was because you did not have the option to customize active tab colours and I was having difficulty locating the active tab when I had lots of open tabs (which is always :) ). 

Edit: Just an update. I have confirmed that Tab Mix Plus is the issue. There were two issues I had, this and one where FF details on title bar disappeared. When I deactivate Tab MIx Plus, both issues are resolved. I have also posted these possible problems on the Tab Mix Plus forum. The first one may be something you can address, or it may be their issue. I don't know. And the two issues may be related. Again, I don't know. But I just wanted to provide you with an update.

**Comment by ludasmokva** [comment]
Just wanted to note that I have included some attachments on the TabMixPlus forum in case you wanted to view the details. I would be happy to attach any of them here as well if you deem it necessary. Let me know.
Here is the direct link to the forum post:
http://tabmixplus.org/forum/viewtopic.php?f=2&t=19870

**Comment by ludasmokva** [comment]
OK. Update:

TMP found the reason for the disappearing "+". 
In their 'New Tab' settings (Display > Tab Bar) the new tab option defaults to 'After Last Tab'. If you choose Left or Right, the "+" will reappear left of the drop arrow. 
As it really doesn't have any other positioning function (left or right does not make any difference), it may be wise to take control of this option and not allow the user to manipulate it.

The title bar is still blank, and (surprise) I think TMP believes it is your issue. :) 
Again, you can follow the details on the link above.
Hopefully this helps.

**Comment by Croydon** [comment]
In the new WebExtension sidebar the new tab symbol can't vanish. I will close this bug therefore.

**Comment by Croydon** [comment]
Thanks for providing all the information :)

**Comment by ludasmokva** [comment]
Works really well. Even the title bar now shows up.
Thank you!!
I will make a note on the tab-mix forum as well that everything is working
fine.
I only recently started using your add-on, and found it kind of weird at
first.
Now I absolutely love it. It is soooooo much easier keeping track of huge
amount of tabs I keep open.
I see it is still marked as legacy, and I really hope you are able to
update it. I'm actually contemplating not upgrading FF unless that happens.
Your add-on has very quickly made it to my top-3 list.
Congrats on making a great and common-sense add-on.  You should be really
proud. :)

**Comment by Croydon** [comment]
@ludasmokva Thanks for your warm words :)

I'm working on porting the add-on to WebExtension see all information at #13.
