### ISSUE TITLE
Big gap between Tabs

### ISSUE THREAD

**Issue by Nemesis31** [Croydon/vertical-tabs-reloaded#109]
Hi,

Add-on version: 0.8.3.1
Firefox version: 54.0.1 (64 bits)
OS + OS-Version: W10 64 bits
Other tab + user interface related add-ons: Stylish with Firefox Black

Sometimes, when i open another tab (blank tab or filled one), a gap is created, like on the screenshot.
I tried to reproduce it, but, it's like, random.

https://up2sha.re/media/raw/r3HFKaNA.png

**Comment by Croydon** [comment]
@Nemesis31 What VTR theme are you using?

**Comment by Nemesis31** [comment]
Hello, if I remember well, i tried the default and the dark one. But I'm not at home so... When i return (around the 20th), I'll try some tests (like running Firefox with a clean profile).

**Comment by Nemesis31** [comment]
Hi there,

with clean profile, the add-on is working fine. So i tried again with my profile.... not working, but the problem was not the gap now, it was an overlapping between the menu with all the icons and the Title menu of Firefox.

So, i decided to re-install VTR and now, all is working fine ! :D

**Comment by Croydon** [comment]
@Nemesis31 You could have just toggle the title bar within the VTR settings.

However, if everything works fine then nice :)
