### ISSUE TITLE
Fullscreen in Firefox 55 Release broken

### ISSUE THREAD

**Issue by Croydon** [Croydon/vertical-tabs-reloaded#110]
Well, I was thinking Firefox Beta is there for testing...

Anyway, fullscreen is broken in FF55 release right now, while apparently working in all other versions, including Firefox Beta 55...?

The problem is that I won't be near any computer till next Monday, so there won't be a fix till then.

In the meantime: you can use the keyboard shotcut for hiding the tab browser BEFORE going into fullscreen, then undo it when exiting fullscreen. Still annoying but better than having the tabbrowser visible all the time.

Sorry!

**Comment by xxTheGoDxx** [comment]
Same behavior here, thanks a lot for the headsup.

**Comment by edduarte** [comment]
Strange, I even mentioned this before, during the beta phase: https://github.com/Croydon/vertical-tabs-reloaded/issues/99#issuecomment-309169895

Any follow up on this?

Thanks for the all hard work.

**Comment by grahamperrin** [comment]
0.8.5-alpha working as expected. Thanks.
