### ISSUE TITLE
VTR button (icon in the toolbar of Firefox) route to preferences for Vertical Tabs Reloaded 

### ISSUE THREAD

**Issue by grahamperrin** [Croydon/vertical-tabs-reloaded#115]
From critical <https://github.com/Croydon/vertical-tabs-reloaded/issues/42#issuecomment-326489533>:

> … since critical full-screen issue #110 is fixed (0.8.5-alpha ), there seems to be a slightly increased risk of 42 biting …

## Enhancement request

If it's not too much work, please add a user preference to prevent hiding of the side bar. 

### First thought 

A pin within the grey area at the head of the bar (or the foot, where some users prefer that bar). 

### Second thought

Something other than a pin (because a pin might be misinterpreted as tab-specific). The action is sidebar-specific. 

### Third thought

Maybe a pause icon, 

⏸

There might be a more suitable icon, but as this enhancement request is for a limited range of versions of Firefox (55.x and 56.x alone) I should not treat _choice of icon_ as critical. 

### Fourth thought

Instead of a separate icon within the sidebar, enhance the existing **VTR** button. It's currently: 

- a simple switch, with no visible change to the button when enabled. 

Maybe add a drop-down from the VTR button, exposing the preference. 

Three states to the button, refraining from use of colour (greyscale is good): 

- normal (with the window-like border to the button)
- sidebar hidden on demand – I suggest greying-out the three letters (VTR)
- sidebar never hidden – I suggest the three letters (VTR), black, heavier, _without_ the window-like border. 

…

**Comment by grahamperrin** [comment]
I completely forgot – 

![2017-09-01 07 20 24 add-ons manager](https://user-images.githubusercontent.com/192271/29957613-52a276fe-8ee6-11e7-987f-f78d9453dbed.png)

– we already have the preference in the `about:addons` interface to Vertical Tabs Reloaded. 

(Sorry! Maybe I had become word-blind to the preference, from it not working in the past.)

----

I'll leave this ER open, for consideration of the toolbar icon; the toolbar is relatively handy/immediate. 

(The steps in to, and out of, `about:addons` can be relatively tedious.)

**Comment by Croydon** [comment]
For the new WebExtension version I planned to add an option symbol to the toolbar (this is what you called "grey area at the head of the bar") which opens the preference page within about:addons

What are your thoughts about this solution?

**Comment by grahamperrin** [comment]
Defocusing from Vertical Tabs Reloaded: I _never_ enjoy Mozilla's `about:addons` interface to extension-specific preferences. It's necessary to page down before preferences begin to appear, and so on. 

----

For VTR: I reckon, the future ideal will be a drop-down (pop-over) from the button, with the space focused solely on the full set of preferences for the extension. 

In the meantime … yes, it will be helpful if users can step from the VTR button to a relevant part of `about:addons`.

**Comment by Croydon** [comment]
I have added now an option icon to the new WebExtension sidebar, which opens the about:addons options page. Further improvements might come in the future. In specific I'm hoping that https://bug623317.bugzilla.mozilla.org/show_bug.cgi?id=1253419 is getting implemented soon into Firefox.

![webext](https://user-images.githubusercontent.com/1593194/30341623-0696c246-97f7-11e7-9c0d-a399cdf8a26d.PNG)

**Comment by Croydon** [comment]
Also I have shorten a bit the add-on description because it is indeed a user experience problem, that they have to scroll down first.
