### ISSUE TITLE
Preferences are not loading in Firefox 55

### ISSUE THREAD

**Issue by jonasflint** [Croydon/vertical-tabs-reloaded#116]
Preferences are not loading. I'm getting a spinning loader: 

http://d.pr/i/TFDrf4

Add-on version: .08.4.1
Firefox version: 55
OS + OS-Version: Mac OSx Sierra 64bit
Other tab + user interface related add-ons:

**Comment by grahamperrin** [comment]
Hi @jonasflint 

Your screenshot shows the absence of a screenshot. 

Not reproducible with 0.8.5-alpha on Firefox 55.0.3 (64-bit) on FreeBSD-CURRENT: 

![2017-09-09 07 20 47 add-ons manager](https://user-images.githubusercontent.com/192271/30237733-069c0658-9530-11e7-9b82-d5cf95485d63.png)

![2017-09-09 07 22 02 add-ons manager](https://user-images.githubusercontent.com/192271/30237732-06966342-9530-11e7-87c6-932f6714295d.png)

With 0.8.4.1: if you scroll down past where the screenshot should appear, then do you find preferences (comparable to those shown above)?

Consider the possibility of an extension conflict. A visit to `about:support` will allow you to copy relevant information, which includes information about extensions that are enabled.

**Comment by jonasflint** [comment]
updated screenshot: http://d.pr/i/ViZ32Z

here is my about:support data:  
`{
  "application": {
    "name": "Firefox",
    "osVersion": "Darwin 16.7.0",
    "version": "55.0.3",
    "buildID": "20170824053838",
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0",
    "safeMode": false,
    "updateChannel": "release",
    "supportURL": "https://support.mozilla.org/1/firefox/55.0.3/Darwin/en-US/",
    "numTotalWindows": 1,
    "numRemoteWindows": 0,
    "remoteAutoStart": false,
    "currentContentProcesses": 0,
    "maxContentProcesses": 1,
    "autoStartStatus": 7,
    "keyGoogleFound": true,
    "keyMozillaFound": true
  },
  "modifiedPreferences": {
    "accessibility.typeaheadfind.flashBar": 0,
    "browser.cache.disk.filesystem_reported": 1,
    "browser.cache.disk.hashstats_reported": 1,
    "browser.cache.frecency_experiment": 3,
    "browser.cache.disk.smart_size.first_run": false,
    "browser.cache.disk.smart_size.use_old_max": false,
    "browser.cache.disk.capacity": 358400,
    "browser.download.manager.alertOnEXEOpen": true,
    "browser.download.useDownloadDir": false,
    "browser.places.smartBookmarksVersion": 8,
    "browser.sessionstore.upgradeBackup.latestBuildID": "20170824053838",
    "browser.startup.homepage_override.mstone": "55.0.3",
    "browser.startup.homepage_override.buildID": "20170824053838",
    "browser.tabs.warnOnClose": false,
    "browser.tabs.remote.autostart.2": true,
    "browser.urlbar.lastSuggestionsPromptDate": 20170818,
    "browser.urlbar.timesBeforeHidingSuggestionsHint": 0,
    "browser.urlbar.daysBeforeHidingSuggestionsPrompt": 0,
    "dom.apps.lastUpdate.buildID": "20161019084923",
    "dom.max_script_run_time": 0,
    "dom.apps.reset-permissions": true,
    "dom.apps.lastUpdate.mstone": "49.0.2",
    "dom.mozApps.used": true,
    "extensions.lastAppVersion": "55.0.3",
    "font.internaluseonly.changed": true,
    "gfx.crash-guard.glcontext.deviceID": "0x944a",
    "gfx.crash-guard.glcontext.appVersion": "45.0.1",
    "gfx.crash-guard.status.glcontext": 2,
    "media.webrtc.debug.log_file": "/Users/jive/Library/Caches/TemporaryItems/WebRTC.log",
    "media.benchmark.vp9.versioncheck": 2,
    "media.gmp-widevinecdm.lastUpdate": 1493128873,
    "media.gmp-gmpopenh264.lastUpdate": 1493128872,
    "media.gmp-gmpopenh264.abi": "x86_64-gcc3",
    "media.gmp-manager.lastCheck": 1505142425,
    "media.gmp-widevinecdm.abi": "x86_64-gcc3",
    "media.gmp-widevinecdm.version": "1.4.8.903",
    "media.gmp.storage.version.observed": 1,
    "media.benchmark.vp9.fps": 150,
    "media.gmp-gmpopenh264.version": "1.6",
    "media.gmp-manager.buildID": "20170824053838",
    "network.predictor.cleaned-up": true,
    "network.cookie.prefsMigrated": true,
    "places.history.expiration.transient_current_max_pages": 123848,
    "places.database.lastMaintenance": 1505054642,
    "plugin.importedState": true,
    "plugin.disable_full_page_plugin_for_types": "application/pdf",
    "plugins.ctprollout.cohortSample": "0.030548",
    "plugins.ctprollout.cohort": "test",
    "print.print_paper_width": "  8.50",
    "print.print_to_file": false,
    "print.print_margin_top": "0.5",
    "print.print_paper_name": "",
    "print.print_reversed": false,
    "print.print_orientation": 0,
    "print.print_paper_height": " 11.00",
    "print.print_scaling": "  1.00",
    "print.print_unwriteable_margin_right": 20,
    "print.print_unwriteable_margin_left": 20,
    "print.print_paper_size_unit": 0,
    "print.print_unwriteable_margin_bottom": 20,
    "print.print_margin_right": "0.5",
    "print.print_paper_data": 0,
    "print.print_oddpages": true,
    "print.print_bgcolor": false,
    "print.print_bgimages": false,
    "print.print_duplex": -437918235,
    "print.print_evenpages": true,
    "print.print_margin_bottom": "0.5",
    "print.print_margin_left": "0.5",
    "print.print_shrink_to_fit": true,
    "print.print_unwriteable_margin_top": 20,
    "print.print_in_color": true,
    "print.print_page_delay": 50,
    "print.print_resolution": -437918235,
    "privacy.sanitize.migrateClearSavedPwdsOnExit": true,
    "privacy.sanitize.migrateFx3Prefs": true,
    "security.sandbox.content.tempDirSuffix": "{b1ff4380-41cb-fe43-aec5-57c849f1f50f}",
    "services.sync.declinedEngines": "",
    "storage.vacuum.last.places.sqlite": 1504446794,
    "storage.vacuum.last.index": 1
  },
  "lockedPreferences": {},
  "javaScript": {
    "incrementalGCEnabled": true
  },
  "accessibility": {
    "isActive": false,
    "forceDisabled": 0
  },
  "libraryVersions": {
    "NSPR": {
      "minVersion": "4.15",
      "version": "4.15"
    },
    "NSS": {
      "minVersion": "3.31.1",
      "version": "3.31.1"
    },
    "NSSUTIL": {
      "minVersion": "3.31.1",
      "version": "3.31.1"
    },
    "NSSSSL": {
      "minVersion": "3.31.1",
      "version": "3.31.1"
    },
    "NSSSMIME": {
      "minVersion": "3.31.1",
      "version": "3.31.1"
    }
  },
  "userJS": {
    "exists": false
  },
  "crashes": {
    "submitted": [],
    "pending": 0
  },
  "sandbox": {
    "contentSandboxLevel": 1,
    "effectiveContentSandboxLevel": 1
  },
  "graphics": {
    "numTotalWindows": 1,
    "numAcceleratedWindows": 1,
    "windowLayerManagerType": "OpenGL",
    "windowLayerManagerRemote": true,
    "currentAudioBackend": "audiounit",
    "adapterDescription": "",
    "adapterVendorID": "0x1002",
    "adapterDeviceID": "0x944a",
    "adapterRAM": "",
    "adapterDrivers": "",
    "driverVersion": "",
    "driverDate": "",
    "webgl1Renderer": "ATI Technologies Inc. -- ATI Radeon HD 4850 OpenGL Engine",
    "webgl1Version": "2.1 ATI-10.2.37",
    "webgl1DriverExtensions": "GL_ARB_color_buffer_float GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_draw_buffers GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_imaging GL_ARB_instanced_arrays GL_ARB_multisample GL_ARB_multitexture GL_ARB_occlusion_query GL_ARB_pixel_buffer_object GL_ARB_point_parameters GL_ARB_point_sprite GL_ARB_provoking_vertex GL_ARB_seamless_cube_map GL_ARB_shader_objects GL_ARB_shader_texture_lod GL_ARB_shading_language_100 GL_ARB_shadow GL_ARB_shadow_ambient GL_ARB_sync GL_ARB_texture_border_clamp GL_ARB_texture_compression GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map GL_ARB_texture_env_add GL_ARB_texture_env_combine GL_ARB_texture_env_crossbar GL_ARB_texture_env_dot3 GL_ARB_texture_float GL_ARB_texture_mirrored_repeat GL_ARB_texture_non_power_of_two GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_transpose_matrix GL_ARB_vertex_array_bgra GL_ARB_vertex_blend GL_ARB_vertex_buffer_object GL_ARB_vertex_program GL_ARB_vertex_shader GL_ARB_window_pos GL_EXT_abgr GL_EXT_bgra GL_EXT_bindable_uniform GL_EXT_blend_color GL_EXT_blend_equation_separate GL_EXT_blend_func_separate GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_clip_volume_hint GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_draw_buffers2 GL_EXT_draw_range_elements GL_EXT_fog_coord GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_geometry_shader4 GL_EXT_gpu_program_parameters GL_EXT_gpu_shader4 GL_EXT_multi_draw_arrays GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_provoking_vertex GL_EXT_rescale_normal GL_EXT_secondary_color GL_EXT_separate_specular_color GL_EXT_shadow_funcs GL_EXT_stencil_two_side GL_EXT_stencil_wrap GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_s3tc GL_EXT_texture_env_add GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_lod_bias GL_EXT_texture_mirror_clamp GL_EXT_texture_rectangle GL_EXT_texture_shared_exponent GL_EXT_texture_sRGB GL_EXT_texture_sRGB_decode GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_APPLE_aux_depth_stencil GL_APPLE_client_storage GL_APPLE_element_array GL_APPLE_fence GL_APPLE_float_pixels GL_APPLE_flush_buffer_range GL_APPLE_flush_render GL_APPLE_object_purgeable GL_APPLE_packed_pixels GL_APPLE_pixel_buffer GL_APPLE_rgb_422 GL_APPLE_row_bytes GL_APPLE_specular_vector GL_APPLE_texture_range GL_APPLE_transform_hint GL_APPLE_vertex_array_object GL_APPLE_vertex_array_range GL_APPLE_vertex_point_size GL_APPLE_vertex_program_evaluators GL_APPLE_ycbcr_422 GL_ATI_blend_equation_separate GL_ATI_blend_weighted_minmax GL_ATI_separate_stencil GL_ATI_texture_compression_3dc GL_ATI_texture_env_combine3 GL_ATI_texture_float GL_ATI_texture_mirror_once GL_IBM_rasterpos_clip GL_NV_blend_square GL_NV_conditional_render GL_NV_depth_clamp GL_NV_fog_distance GL_NV_light_max_exponent GL_NV_texgen_reflection GL_NV_texture_barrier GL_SGI_color_matrix GL_SGIS_generate_mipmap GL_SGIS_texture_edge_clamp GL_SGIS_texture_lod ",
    "webgl1Extensions": "ANGLE_instanced_arrays EXT_blend_minmax EXT_color_buffer_half_float EXT_frag_depth EXT_sRGB EXT_shader_texture_lod EXT_texture_filter_anisotropic MOZ_debug OES_element_index_uint OES_standard_derivatives OES_texture_float OES_texture_float_linear OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_depth_texture WEBGL_draw_buffers WEBGL_lose_context MOZ_WEBGL_lose_context MOZ_WEBGL_compressed_texture_s3tc MOZ_WEBGL_depth_texture",
    "webgl1WSIInfo": "CGL",
    "webgl2Renderer": "WebGL creation failed: \n* WebGL 2 requires support for the following features: \n  transform_feedback2\n* Exhausted GL driver options.",
    "webgl2Version": "-",
    "webgl2DriverExtensions": "-",
    "webgl2Extensions": "-",
    "webgl2WSIInfo": "-",
    "info": {
      "AzureCanvasBackend": "skia",
      "AzureFallbackCanvasBackend": "none",
      "AzureContentBackend": "skia",
      "AzureCanvasAccelerated": 1,
      "TileHeight": 1024,
      "TileWidth": 1024
    },
    "featureLog": {
      "features": [
        {
          "name": "HW_COMPOSITING",
          "description": "Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "OPENGL_COMPOSITING",
          "description": "OpenGL Compositing",
          "status": "available",
          "log": [
            {
              "type": "default",
              "status": "available"
            }
          ]
        },
        {
          "name": "WEBRENDER",
          "description": "WebRender",
          "status": "unavailable",
          "log": [
            {
              "type": "default",
              "status": "opt-in",
              "message": "WebRender is an opt-in feature"
            },
            {
              "type": "runtime",
              "status": "unavailable",
              "message": "Build doesn't include WebRender"
            }
          ]
        }
      ],
      "fallbacks": []
    },
    "crashGuards": []
  },
  "experiments": [],
  "extensions": [
    {
      "name": "All-in-One Sidebar",
      "version": "0.7.31.1",
      "isActive": true,
      "id": "{097d3191-e6fa-4728-9826-b533d755359d}"
    },
    {
      "name": "Auto Reload",
      "version": "1.22",
      "isActive": true,
      "id": "autoreload@yz.com"
    },
    {
      "name": "DevTools Prototyper",
      "version": "4.5.1",
      "isActive": true,
      "id": "devtools-prototyper@tim-addons.com"
    },
    {
      "name": "DOM Inspector",
      "version": "2.0.16.1-signed",
      "isActive": true,
      "id": "inspector@mozilla.org"
    },
    {
      "name": "FireFTP",
      "version": "2.0.31",
      "isActive": true,
      "id": "{a7c6cf7f-112c-4500-a7ea-39801a327e5f}"
    },
    {
      "name": "In My Pocket",
      "version": "0.5.2",
      "isActive": true,
      "id": "{cd7e22de-2e34-40f0-aeff-cec824cbccac}"
    },
    {
      "name": "Tab Groups",
      "version": "2.1.4",
      "isActive": true,
      "id": "tabgroups@quicksaver"
    },
    {
      "name": "Tab Groups Button",
      "version": "0.53.2",
      "isActive": true,
      "id": "tabgroupsbtn@char101.github.com"
    },
    {
      "name": "Tab Mix Plus",
      "version": "0.5.0.4",
      "isActive": true,
      "id": "{dc572301-7619-498c-a57d-39143191b318}"
    },
    {
      "name": "Vertical Tabs Reloaded",
      "version": "0.8.4.1",
      "isActive": true,
      "id": "verticaltabsreloaded@go-dev.de"
    },
    {
      "name": "Web Developer",
      "version": "1.2.13",
      "isActive": true,
      "id": "{c45c406e-ab73-11d8-be73-000a95be3b12}"
    },
    {
      "name": "Window Master",
      "version": "7.5",
      "isActive": true,
      "id": "monitormaster@pjs.nl"
    },
    {
      "name": "Adobe Acrobat DC - Create PDF",
      "version": "15.01.04",
      "isActive": false,
      "id": "web2pdfextension@web2pdf.adobedotcom"
    },
    {
      "name": "Vertical Tabs (Simplified)",
      "version": "0.1",
      "isActive": false,
      "id": "verticaltabs-simplified@mozilla.com"
    }
  ],
  "features": [
    {
      "name": "Application Update Service Helper",
      "version": "2.0",
      "id": "aushelper@mozilla.org"
    },
    {
      "name": "Click-to-Play staged rollout",
      "version": "1.2",
      "id": "clicktoplay-rollout@mozilla.org"
    },
    {
      "name": "Firefox Screenshots",
      "version": "10.12.0",
      "id": "screenshots@mozilla.org"
    },
    {
      "name": "Follow-on Search Telemetry",
      "version": "0.9.3",
      "id": "followonsearch@mozilla.com"
    },
    {
      "name": "Multi-process staged rollout",
      "version": "2.0",
      "id": "e10srollout@mozilla.org"
    },
    {
      "name": "Pocket",
      "version": "1.0.5",
      "id": "firefox@getpocket.com"
    },
    {
      "name": "Shield Recipe Client",
      "version": "55.1",
      "id": "shield-recipe-client@mozilla.org"
    },
    {
      "name": "Web Compat",
      "version": "1.1",
      "id": "webcompat@mozilla.org"
    }
  ]
}`

**Comment by jonasflint** [comment]
I found the conflict. It's a conflict with vertical tabs relaoded.   I disabled that and it's fine.

**Comment by Croydon** [comment]
Alright. Thanks for reporting. Since All In One Sidebar is a legacy add-on which can't be updated to WebExtensions it will stop working with FF57, therefore I will not try to find a fix for compatibility.
