### ISSUE TITLE
Middle-click considered harmful

### ISSUE THREAD

**Issue by belg4mit** [Croydon/vertical-tabs-reloaded#118]
Add-on version: 0.8.4.1
Firefox version: Waterfox
OS + OS-Version: Windows 10
Other tab + user interface related add-ons: 

Having tabs closed due to middle-clicking is insidious and evil, especially since it is possible to accidentally middle click when using a scroll wheel. At a minimum, this should be optional.

**Comment by Croydon** [comment]
This is not caused by VTR, but rather Firefox itself.

However, on the upside, the upcoming WebExtension version of VTR won't have this behaviour anymore 😄
