### ISSUE TITLE
Complete context menu options

### ISSUE THREAD

**Issue by Croydon** [Croydon/vertical-tabs-reloaded#120]
Blocked by #13. The initial full WebExtension version won't have all context menu options there are right now available. This issue collects what still needs to get implemented:

* [x] Move to New Window (3600cb1, 0.10.0a2)
  * [x] Problem: Sidebar isn't open in the new window
    * This was fixed in Firefox somewhere along the way, it's at last in FF 62.0a1
* [x] Close All Tabs Above (43770b0, 0.10.0a2)
* [x] Close All Tabs Below (550b177, 0.10.0a2)
* [x] Close All Other Tabs (5a3e323, 0.10.0a2)
* [x] Undo Close Tab (6af289f, 0.11.0a11)
* ~~Send tab to device~~ -> #178
* [x] Reload all tabs (576bb10, 0.10.0a2)
* [x] Bookmark all tabs (95fe4ac, 0.11a23)
* [x] Unload tab (this is not a Firefox default) (dd950e7, 0.11.0a11)

**Comment by AWilyFox** [comment]
"Unload tab" to unload a tab but not close it. Really useful to silence those auto-reloading websites that continually reload in background tabs draining resources.

**Comment by dustymabe** [comment]
definitely interested in "Undo Close Tab"

**Comment by Croydon** [comment]
@dustymabe Would you expect from this feature to re-open only the very last tab or all tabs which were closest in the last "close step"?

**Comment by dustymabe** [comment]
the way it works in the TST extension is to re-open the last closed tab. From your question it makes it seem like a user can close multiple tabs in a single "step". I don't know how to do that or I don't actually use it if I do. Re-opening just the last closed tab would be good enough for me.

A bonus would be if the 'recently closed tabs' were a stack where I can right click and 'undo closed tab' multiple times to get to other recently closed tabs.

**Comment by Luckz** [comment]
Re unloading, https://bugzilla.mozilla.org/show_bug.cgi?id=1415918 is in FF59, ye?

**Comment by Croydon** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1376251

**Comment by Croydon** [comment]
All of these features will be in the 0.11.0 release.
