### ISSUE TITLE
Probably not a bug... but what the heck is it and what does it do?

### ISSUE THREAD

**Issue by ludasmokva** [Croydon/vertical-tabs-reloaded#124]
Add-on version: 0.8.4.1
Firefox version: 55.0.3 32-bit
OS + OS-Version: Win 7
Other tab + user interface related add-ons:  Tab Mix Plus, Private Tab (??)

So.. in an effort to reorganize my tabs, I happened to resort to the windows technique where I press SHIFT or CTRL to select multiple tabs. The result was somewhat strange... an exclamation point appeared on the tab with SHIFT and an additional asterix with CTRL.  (See attached image).

![multiselection](https://user-images.githubusercontent.com/11639404/30624931-28ddd136-9d8e-11e7-978f-eacd013c78f2.png)

Going to other tabs (ie. deselecting tab) did not make it disappear. It took me a while to figure out that only by redoing the action (pressing SHIFT or CTRL on the tab)  makes the exclamation point and/or asterix vanish. 
So I don't really think it is a bug as it doesn't seem to affect anything. I can move other tabs without a problem, and it does not affect my viewing of the tab. It's just weird.  
So I'm wondering if there is any meaning behind them? Did I activate some hidden feature? Because when you see it on your tab list, the perception is that there is some kind of problem with the tab which - as far as I know - there isn't.

**Comment by Croydon** [comment]
VTR doesn't support multi-select of tabs right now, which means you are using another add-on with this ability. Also, VTR does not add anywhere exclamations points or asterix.

Sorry, I guess I can't really help here  :)

**Comment by ludasmokva** [comment]
Hmmm.... interesting. Could be some kind of default feature in tab mix plus or FF. 
Would have been helpful if they also created a tool tip or right click option that would help identify what the feature is/does.
Oh well, I have enough problems to worry about. No point in spending time identifying something that doesn't really harm anything. But I'm glad I'm not adding to your workload.  :)
(And no, I won't 'suggest' a multi-select tab feature although it would be cool. Your extension is awesome as is.)

**Comment by Croydon** [comment]
Thanks :)

There is already a suggestion: #49 😄
