### ISSUE TITLE
Broken after latest Firefox DE upgrade

### ISSUE THREAD

**Issue by alexander255** [Croydon/vertical-tabs-reloaded#125]
Add-on version: 0.8.5a2
Firefox version: 57.0b1 (FireFox Developer Edition)
OS + OS-Version: Fedora 26
Other tab + user interface related add-ons: None

After having used Vertical Tabs Reloaded (and its predecessors) for many years I now got "upgraded" to FireFox 57.0b1 and could not use VTR Classic anymore. So I installed the latest dev release instead, but it won't work either unfortunately:

![screenshot_20170921_143358](https://user-images.githubusercontent.com/246386/30696167-feb82f48-9eda-11e7-8ce1-d5dfe8406ded.png)

There's a few errors when starting/enabling the extension, then the toolbar icon appears, but clicking on does nothing except for writing another line of:

```
Error: Could not establish connection. Receiving end does not exist.
```

**Comment by Croydon** [comment]
Open a build-in sidebar, then select VTR in the drop-down options. This should work.

**Comment by alexander255** [comment]
Thanks! That was a bit non-obvious, but now it works! :+1:

**Comment by Croydon** [comment]
I know, I'm working on it :)

**Comment by Croydon** [comment]
Another hint: Use the context menu for a few basic tab options (and yes, that has some display problems on it's own)
