### ISSUE TITLE
Advance Options?

### ISSUE THREAD

**Issue by LookingForWayOut** [Croydon/vertical-tabs-reloaded#131]
Add-on version: 0.8.5.2
Firefox version: 56.0.1 64b
OS + OS-Version: W10
Other tab + user interface related add-ons: 

I clicked on advance options but nothing happens.
I am looking for options to sort by name, opener, etc, and the option for tabs to be opened under parent tab.

Are they there?

Thank you.

**Comment by Croydon** [comment]
> I am looking for options to sort by name, opener, etc, and the option for tabs to be opened under parent tab.

No, VTR has not such options.

The bug is fixed in the WebExtension-only version (currently only in the developer channel), but I won't fix it in the legacy form anymore.

The advanced options are mainly for debugging right now, so you won't miss anything there 😄
