### ISSUE TITLE
Close tab button is huuuuge

### ISSUE THREAD

**Issue by woj-tek** [Croydon/vertical-tabs-reloaded#132]
Add-on version: 0.8.6a1
Firefox version: DevEd 57.0b11 (64-bit)
OS + OS-Version: HighSierra 10.13

With the above configuration the close tab button is huge

**Comment by Croydon** [comment]
Could you please make a screenshot?

**Comment by woj-tek** [comment]
https://www.dropbox.com/s/mjtsndwtlhbfzcz/Captura%20de%20pantalla%202017-10-26%2017.26.53.png?dl=0

**Comment by Croydon** [comment]
@woj-tek Can you please try 0.8.6a5 and report if it's fixed for you?

**Comment by woj-tek** [comment]
I confirm it's fixed. Thank you.
