### ISSUE TITLE
gap between tabs when closing them

### ISSUE THREAD

**Issue by FinnDorian** [Croydon/vertical-tabs-reloaded#14]
The gap between tabs when you close them stays sometimes....
![gap](https://cloud.githubusercontent.com/assets/17819893/13734447/57e765c8-e99e-11e5-9f5a-c1d299a8746c.png)

**Comment by yafp** [comment]
Seems like you are not the only one with this issue. Some were talking already in issue #7 about this effect.

@Croydon:
i can now confirm that i was able to reproduce this issue several times with the old 0.3 version/build. So for me it looks like the issue started before 0.3. and for sure before 0.3.2

Hope that helps

**Comment by Croydon** [comment]
@yafp Thank you for testing! If this is already happening with the 0.3 version then it could be that some change in Firefox broke something somewhere somewhen.

However, I am still clueless why it should happen just sometimes and not even in all Firefox profiles/settings/setups. I will continue to hunt the bug down as soon as I can.

**Comment by xxdavid** [comment]
I think I noticed this gaps on Sunday for the first time. It occurred after I disabled and then enabled again the addon.

**Comment by Croydon** [comment]
@yafp, @xxdavid Could you two please try to do the following:
1) Remove the add-on
2) Close the open Add-on mananger (only then add-ons are getting really removed)
3) Restart Firefox
4) Install the latest version of the add-on

It might have to do something with a corrupt session storage. If you try it, please report back if the bug is still there. Thanks in advance :smile: 

@FinnDorian: Did you installe version 0.3.0 and the bug occured in v0.3.2 OR did you disable/enable the add-on at some point?

**Comment by xxdavid** [comment]
@Croydon, it looks like it works now! Thank you!

**Comment by Croydon** [comment]
@xxdavid Well, it is not fixed yet, but I may have finally a clue where this bug comes from :)

**Comment by yafp** [comment]
@Croydon 
i did so - gonna report back in a few days.

**Comment by FinnDorian** [comment]
@Croydon I did so too, for now the bug seems to have disappeared :) I'm using sessionmanager addon, maybe it has to do something with it?
I can't remember which version I installed first, sorry. But I enabled/disabled my plugins a lot because I compared vertical tabs addons and found yours to be the best ;)

**Comment by Croydon** [comment]
@yafp Thanks. Please note that an update is in the queue. I am expecting that it will work fine till it will update in your Firefox or till you manually disable/enable the current version (don't do this please).

@FinnDorian Nope, no third party is to blame here.

I guess the bug is related to #8: The unload process is broken.

**Comment by Croydon** [comment]
It might be a coincidence, but I don't expierence this bug anymore with v0.5.0. 

@yafp You are already using v0.5.0, do you still have this bug?

**Comment by yafp** [comment]
Yes i am using 0.5.0 already on my working machine, but only for about 1 day. Please give me another day until i give my impression ;)

so far it looks good (had no gaps today), but somehow i am unsure as i wasn't working that much in my browser/firefox today.

**Comment by Croydon** [comment]
@FinnDorian @xxdavid Version v0.5.0 is now out, after the add-on updated itself in your setups and at least one restart of Firefox (I still do not trust the XBL binding updates), could you please report back if this bug still occurs?

**Comment by yafp** [comment]
@Croydon 
hurray .... seems like i can't any longer reproduce the gap-bug with 0.5.0.

**Comment by Croydon** [comment]
I will wait till more people have reported that it is gone, but looks pretty promising right now. :tada:

**Comment by xxdavid** [comment]
I can't reproduce it neither. :+1: Thank you! :smile:

**Comment by Croydon** [comment]
Well...
I never knew what is causing this bug.
Then I refactored a lot of creepy code.
Now it seems to be gone, again no idea why.
This will keep annoying me everytime I think about it, since I couldn't satisfy my curiosity.

But at least it is gone. 🎉

**Comment by Croydon** [comment]
@mbaz & @Marty Just wondering, is it fixed for your two as well?

**Comment by Marty** [comment]
@Croydon yep it's gone, thank you :)
