### ISSUE TITLE
Can't middle click tabs to close them since Firefox 57

### ISSUE THREAD

**Issue by codecat** [Croydon/vertical-tabs-reloaded#143]
Add-on version: 0.9.0
Firefox version: 57.0
OS + OS-Version: Windows 10
Other tab + user interface related add-ons: None

Additionally, middle mouse clicking on the empty space in the tab bar doesn't open a new tab.

**Comment by Croydon** [comment]
This was never a feature of VTR.

It was (is?) a feature of Firefox, which was passing through to VTR.

Due to the sandboxing nature of WebExtensions you notice now just the plain behaviour of VTR itself.

Actually, people compained about that before and categorized this as a bug https://github.com/Croydon/vertical-tabs-reloaded/issues/118

So I'm not sure yet what to do about that...

Single clicking on free space in the tab bar opens a new tab (https://github.com/Croydon/vertical-tabs-reloaded/issues/17). Should be good enough?

**Comment by codecat** [comment]
Double clicking does work, yes, but middle clicking has been a feature of the Firefox tab bar for years! :)

I would also have to say I disagree with the reporter of #118 because of the above reason. I suppose however they were having issues with it while scrolling through a list of tabs, which in that case, having a setting for it probably doesn't hurt.

**Comment by achermes** [comment]
I for one use this feature a lot to quickly close a lot of tabs - after all, it's easier to place your cursor in a bar then on a small X.

**Comment by woj-tek** [comment]
> Actually, people compained about that before and categorized this as a bug #118

That's a single report and there are at least 3 persons in this thread in favour of the feature (me included). And yes - I also do consider middle-click-to-close as very handy feature.

**Comment by codecat** [comment]
> it's easier to place your cursor in a bar then on a small X.

Exactly this, in fact, previously I have explicitly hidden the X on tabs because with middle clidking the X isn't a useful button to see and it just takes space.

**Comment by Croydon** [comment]
> That's a single report 

Yes, but there were also others.

> Middle mouse clicking on the empty space in the tab bar doesn't open a new tab.

I will going to implement this.

I will also add the possibility to close tabs with a middle-click as opt-in.

**Comment by SmaugTheGreat** [comment]
I switched to Tree Style Tabs until this issue is fixed. I think it's very important. Also the X-buttons take up way too much space and don't look pretty.

**Comment by codecat** [comment]
![image](https://user-images.githubusercontent.com/136534/32852933-e28fded0-ca39-11e7-9397-3fd58fbcc632.png)
The text actually goes *under* the close button for me.. :)

**Comment by Croydon** [comment]
Done with 0.10.0a2 / will be done with 0.10.0 stable.

![closemiddleclick](https://user-images.githubusercontent.com/1593194/33226228-3d2a2048-d189-11e7-8c62-ca56ae12532d.png)
