### ISSUE TITLE
Integrate with the current theme

### ISSUE THREAD

**Issue by nt1m** [Croydon/vertical-tabs-reloaded#144]
From 58 onwards, you can get the current theme properties: 

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/theme/getCurrent

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/theme/onUpdated

Why is this useful ?
Integrating with dynamic themes like [VivaldiFox](https://addons.mozilla.org/en-US/firefox/addon/vivaldifox/) or [Container Theme](https://addons.mozilla.org/en-US/firefox/addon/containers-theme/)

A lot of people have expressed their wish to see VivaldiFox work with their favourite sidebar tabs add-on.

**Comment by Croydon** [comment]
Please use the search before reporting issues.

This is a duplicate of #138
