### ISSUE TITLE
Allowing minimization to just icons

### ISSUE THREAD

**Issue by KevinMars** [Croydon/vertical-tabs-reloaded#146]
Add-on version: 0.9.1
Firefox version: 57.0
OS + OS-Version: Mac High Sierra

Hi is it possible to allow minimizing the size until we just see icons. I think there is a way to do it using userChrome.css files but I haven't had a chance to try it out yet.

**Comment by KevinMars** [comment]
Sorry I see this is mentioned already.

**Comment by Croydon** [comment]
Duplicate of #135
