### ISSUE TITLE
Tab context menu doesn't close when clicking outside the sidebar area

### ISSUE THREAD

**Issue by repaxan** [Croydon/vertical-tabs-reloaded#149]
Add-on version: 0.9.1
Firefox version: 57
OS + OS-Version: Windows 10

It only closes when you click elsewhere in the sidebar.

**Comment by Croydon** [comment]
This is tricky. I could make it close when you move with the mouse outside of the sidebar, but this could lead to unwanted closings.

Your scenario is was users would expect, but it would require to inject a script into every single opened website just for this purpose. That would be insane and inappropriate. And would not even work for privileged tabs like most Firefox build-in pages.
