### ISSUE TITLE
can't move/sort tabs anymore

### ISSUE THREAD

**Issue by FinnDorian** [Croydon/vertical-tabs-reloaded#15]
I think I have the problem since the last ff update to 45.0...
I can't move the tabs anymore, nothing happens when I try to drag them up or down...

**Comment by yafp** [comment]
Which addon-version are you using?
Can't reproduce with addon 0.3.2 on Linux running FF 45.0

**Comment by FinnDorian** [comment]
I'm using 0.3.2 on win 10 with FF 45.0... I tried other extensions like side bars/ vertical tabs (simplyfied) etc. and I'm having the same problem with all of them, so I thought it has something to do with the FF update...
I'll try deactivating all my other addons and see if one of them is affecting vertical tabs reloaded...

**Comment by FinnDorian** [comment]
I'm using 0.3.2 on win 10 with FF 45.0... I tried other extensions like side bars/ vertical tabs (simplyfied) etc. and I'm having the same problem with all of them, so I thought it has something to do with the FF update...
I'll try deactivating all my other addons and see if one of them is affecting vertical tabs reloaded...

**Comment by Croydon** [comment]
@FinnDorian The add-on page states that the developer will not longer maintaince it and that it will stop working in Firefox 47. Unfortunately, it seems like you need to search for a replacement anyway. :)
