### ISSUE TITLE
Scrolls to the bottom with tab positioning addons installed

### ISSUE THREAD

**Issue by repaxan** [Croydon/vertical-tabs-reloaded#151]
Add-on version: 0.9.1
Firefox version: 57
OS + OS-Version: Windows 10

With addons such as "Always Right" or "Open Tabs Next to Current" installed, opening a new tab scrolls the sidebar all the way to the bottom, even though the new tab is correctly put next to the current tab.

This seems to be why:
> The WebExtensions API executes tabs.onCreated listeners after the tab is added to the tab strip. This means that with Always Right, if you have a lot of tabs (say, hundreds), you can actually see the tab added to the far end of the tabstrip and then whiz back over to the right of the active tab. It’s dizzying.

https://hacks.mozilla.org/2017/09/always-right-a-webextension-migration-story/

**Comment by Croydon** [comment]
I will check it out. Sounds like a race condition to me. VTR would regularly move the tab around when it's moved by a third-party.

**Comment by Croydon** [comment]
Can you re-test this please with v0.9.2?

**Comment by kristjaneerik** [comment]
Still broken for me.

**Comment by repaxan** [comment]
Yup, still broken for me.

**Comment by Croydon** [comment]
v0.9.3 will make this working **IN SAME CASES**.

No matter what I'm doing it won't be reliable until  https://bugzilla.mozilla.org/show_bug.cgi?id=1387372 is fixed.

This is out of my hands, sorry.

**Comment by NeoRaider** [comment]
Somewhat related, but without any tab-positioning addons involved: the sidebar does *not* scroll to the top when a tab is opened from a pinned tab, even though the tab is created at the top. Will this also be addressed by the fix in v0.9.4, or should I open a separate issue?

**Comment by Croydon** [comment]
Tab placing add-ons should become a lot more reliable with Firefox 61+ thanks to https://bugzilla.mozilla.org/show_bug.cgi?id=1344749

I am currently refactoring a lot of stuff and will revisit the remaining placing issues afterwards.

**Comment by Croydon** [comment]
Now there is https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/newTabPosition

So I don't think there needs to be anything done within VTR.
