### ISSUE TITLE
Pinned tabs always display busy favicon after FF start

### ISSUE THREAD

**Issue by Korodny** [Croydon/vertical-tabs-reloaded#156]
With VTR 0.9.2 on FF 57.0b6 (64 Bit, Debian testing), my pinned tabs do not display their favicon after Firefox's start, instead they show the spinning 'busy' icon forever. The pinned tabs seem to work perfectly fine otherwise, AFAICT. Hiding and reenabling the VTR sidebar using the View->Sidebar->VTR menu item fixes the problem, i.e. after that the actual favicon is displayed.

I'm not running any other tab related extensions (only uBlock and Zim-Clip), but I'm using UserChrome.css to hide the horizontal toolbars and the sidebar header:

#sidebar-header { display: none !important; }
#TabsToolbar { visibility: collapse; }

Removing these didn't change the behaviour of the pinned tabs though.

**Comment by mbaz** [comment]
I also see this behavior, but not only with pinned tabs (of which I have none). It's hard to pinpoint exactly what happens, but upon launching Firefox, the restored foreground tabs seem to have the spinning icon forever.

FF 57.0, 64 bits, Linux Arch, VTR 0.9.4, no other tab-related extensions.

**Comment by mbaz** [comment]
FF 59.0.2, VTR 0.10.0.

I have about five windows open with maybe 20-30 tabs each. Random tabs are selected (active) in each window. When I restart Firefox, some of the active tabs do not show a favicon (all inactive tabs do). Upon reload, _some_ of the time I get the site's favicon, and some of the time I get the busy favicon.

**Comment by Croydon** [comment]
@mbaz I did some refactoring concerning the creation and updating of tabs. Could you temporary switch to the dev version and report back please if these errors are gone? I have a hard time reproducing the problems so I can't tell if my refactoring did help in these cases.

https://addons.mozilla.org/en-US/firefox/addon/vtr-developer-version/

**Comment by mbaz** [comment]
@Croydon I will, but it might take me a couple of days.

**Comment by Croydon** [comment]
You might actually wait for another few days, since multiple windows are making problems right now.

**Comment by mbaz** [comment]
OK, I'll wait until further notice.

**Comment by Croydon** [comment]
@mbaz Feel free to re-test now :)
