### ISSUE TITLE
Tab toolbar buttons don't react on clicks

### ISSUE THREAD

**Issue by ludasmokva** [Croydon/vertical-tabs-reloaded#159]
Add-on version: 0.9.4
Firefox version: 57 64-bit
OS + OS-Version: Win 7
Other tab + user interface related add-ons: Tab Mix Plus... but just deleted it as it is legacy

Soooo... I think I am missing something.
I can't add new tab.
There is a '+' and gear/sun icon at the bottom, but when I press them, nothing happens.
I am not sure how to add a new tab without going to the menu.
I am pretty certain that it is probably user error :), but for the life of me, this user can't figure it out.

Quick note: My tabs are on the right... could that have something to do with it?
***EDIT: Typo re FF version; meant to put 57 but noticed it said 54. Sorry for any confusion.

**Comment by Croydon** [comment]
Quick workaround: Ctrl+T opens a new tab, should be faster than opening via menu.

The + in the tab toolbar should work, I have a closer look later.

**Comment by ludasmokva** [comment]
:) Thanks. Workaround is good for now.  
I'll try a few other things on my end as well and let you know if something pops.

**Comment by ludasmokva** [comment]
Quick Update:

Just wanted to let you know that this issue remains after a restart of FF; full shut-down & restart of computer; loading FF without add-ons and then restarting FF.  
I cannot get any interaction with the + or gear sign. Not even tooltips (if they exist). They act like embedded images.  
Know you are busy, but wanted to give you a quick update. Was hoping a full restart etc.. would fix it but now see it is not the case.

**Comment by Croydon** [comment]
@ludasmokva Could you please re-test with 0.10.0?

**Comment by ludasmokva** [comment]
Hi! Upgraded to 0.10.0... but nothing changed. The "+" and gear icons still do not respond in any way.
:(  
They just sit there... mocking me.... daring me to make them work. ;)

**Comment by Croydon** [comment]
Does the options button work?

**Comment by ludasmokva** [comment]
No. They are like background images; visible, but no reaction to
mouse-overs and certainly no apparent links or menus associated with them.

**Comment by ludasmokva** [comment]
No problem. I would be happy to try the development version.
Quick question though... when I went to the link you gave me it showed two
options. One was to 'Add to Firefox' and the other was 'You may want to go
here....'. Are both the same? I am thinking that the latter may be for the
current stable version.
Just want to make certain I load the proper one.

**Comment by Croydon** [comment]
> Are both the same? I am thinking that the latter may be for the current stable version.

This is correct. I added the "you might want to go here" notice for people who are accidentally stumble over the dev version and don't understand what it is about 😄 

> Did you press a magic button or something on your end?

I wish I would own something like this :)

Sounds like you have (or had?) more generic issues with your Firefox and/or OS?

Anyway, happy that it's working now.
