### ISSUE TITLE
Provide option to make tab tooltips show the URLs, not the Title of sites

### ISSUE THREAD

**Issue by AWilyFox** [Croydon/vertical-tabs-reloaded#163]
Add-on version: 0.9.4
Firefox version: 57.1
OS + OS-Version: Windows 8.1 and Mac OS X 10
Other tab + user interface related add-ons: No others during my experiment

The site titles are already shown in the tab sidebar, so it is redundant to show them in the tab tooltips as well. It would be much more useful to show the site URL in the tooltip when hovering over a tab, or to provide an option to make it work like that. Currently there is no (easy) way to find out the URL in a tab without clicking on the tab and looking at the URL bar.

**Comment by AWilyFox** [comment]
There was an addon called url-in-tab-tooltip for old Firefox which implemented this, although it seems to have been removed from addons.mozilla.org

**Comment by Croydon** [comment]
It is not redudant as the title is often too long to be completely visible in the sidebar. The tooltip enables users to read the entire title.

There will be a new option in 0.11.0+

![tooltip](https://user-images.githubusercontent.com/1593194/38268103-91df4c58-377d-11e8-9e1d-6dca656ba66f.PNG)

Default remains title only.

**Comment by AWilyFox** [comment]
Perfect! Thanks
