### ISSUE TITLE
Middle-click sometimes opens tab above current tab

### ISSUE THREAD

**Issue by mbaz** [Croydon/vertical-tabs-reloaded#164]
Add-on version: 0.10.0a3
Firefox version: 57.0
OS + OS-Version: Arch Linux
Other tab + user interface related add-ons:  none

Most of the time, middle-clicking on a link opens a tab below the current tab. Sometimes (maybe 5% of time), though, it opens above the current tab. So far I have been unable to identify when this happens; I have also been unable to reproduce this behavior consistently. I will post more details when I have them.

**Comment by mbaz** [comment]
Today, it just happened that middle-clicking a link opened it at the very end of the tab stack, not below the current tab. I suspect something is wrong in the logic that decides where to open a new tab.

**Comment by Croydon** [comment]
Actually, what SHOULD happen right now is that new tabs always open at the very end. This is the default Firefox behavior and doesn't get purposefully changed by VTR  at the moment. So this is rather curious to me.

**Comment by Croydon** [comment]
There is an open issue for supporting third-party add-ons which change this behavior: #151 

This issue is blocked right now by missing features in the WebExtension APIs. I rather don't want to implement this as an native feature in VTR as it has not much to do with vertical tabs on it's own.

**Comment by mbaz** [comment]
Well, that's interesting. Until this morning, on this particular window, middle-clicking has opened tabs right below the current one.

**Comment by mbaz** [comment]
Here's a screencast of a tab opening above the current one. This happens even though I installed the "always right" extension to try it out: https://imgur.com/5jI4az9

**Comment by Croydon** [comment]
@mbaz Please let me know if this still happens in 0.10.0+

**Comment by mbaz** [comment]
Seems to be working! Thank you.
