### ISSUE TITLE
Dynamically shorten tab titles when changing width of tab sidebar

### ISSUE THREAD

**Issue by JervisTetch** [Croydon/vertical-tabs-reloaded#165]
Add-on version: 0.9.4
Firefox version: 57.0.1 (64-Bit)
OS + OS-Version: Slackware Linux (64-Bit, Kernel 4.4.88)
Other tab + user interface related add-ons: -

When changing the width of the tab sidebar all visible tab titles should be shortened like:

`reddit: the front page of the internet` -> `reddit: the fron...`

depending on the current width of the sidebar. Only cosmetical but I think it gives the sidebar some sort of tidiness.

**Comment by Croydon** [comment]
The problem with this is that less letters of the title can be actually displayed as without the dots.

**Comment by JervisTetch** [comment]
That's a point. But I would also be happy with cutting off the width after x pixels.

**Comment by alexander255** [comment]
@Croydon:
Have you considered you considered using [`text-overflow: ellipsis;`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow)? (Asking just in case.)

**Comment by Croydon** [comment]
@JervisTetch What exactly do you mean with cutting off? This is already happening right now?

@alexander255 Yes, I would use it if I wanted to have the three dots at the end, but I don't see any advantage in it and the disadvantage of even less space for the title itself.
