### ISSUE TITLE
Not compatible with Waterfox 56.0.4.1 (64-bit) (I filled "Firefox version" with Waterfox version"

### ISSUE THREAD

**Issue by titanium12345** [Croydon/vertical-tabs-reloaded#170]
Add-on version: 0.9.4
Firefox version: 56.0.4.1
OS + OS-Version: Ubuntu 17.10 x86_64

Other tab + user interface related add-ons: Classic Theme Restorer, Hide Caption Titlebar Plus, Menu Wizard

**Comment by Croydon** [comment]
I don't support Waterfox explicit. 

From my understandig Waterfox doesn't support WebExtensions at all. Therefore the newest version which could work is 0.7.1 https://addons.mozilla.org/de/firefox/addon/vertical-tabs-reloaded/versions/?page=1#version-0.7.1

Duplicate of #166.
