### ISSUE TITLE
Deleting wrong tab

### ISSUE THREAD

**Issue by mmktomato** [Croydon/vertical-tabs-reloaded#177]
I found a bug aboud deleting tabs.

VTR: 0.10.0
FireFox: 59.0.2
OS: macOS 10.13.4

## what I did

1. Add many tabs to overflow the tab panel.
1. In last 3 tabs, open any urls.
    1. Bing
    1. Yahoo
    1. Google
1. Focus last tab (Google).
1. Delete the second tab from the last (Yahoo).
1. Delete the second tab from the last (Bing) without moving mouse pointer.

Then, the 'Google' tab is deleted instead of the 'Bing' one.
I expect to delete 'Bing' tabs.

![captured](https://user-images.githubusercontent.com/1475850/38413075-aa4c57b4-39c5-11e8-94bf-323f4f1c06ff.gif)

**Comment by Croydon** [comment]
Does the error only occur when you DON'T move the mouse pointer?
Meaning, when you close tab 2, move the mouse pointer away from the close button, move the mouse pointer back on the close button from tab 1, click on the close button, the correct tab is getting closed?

**Comment by mmktomato** [comment]
> Does the error only occur when you DON'T move the mouse pointer?
No. This problem is NOT caused when I move the mouse pointer.

> Meaning, when you close tab 2, move the mouse pointer away from the close button, move the mouse > pointer back on the close button from tab 1, click on the close button, the correct tab is getting closed?
Yes.
1. I move the mouse pointer out from close button.
2. Get the mouse pointer back on the close button.
3. Click it.
Then, the correct tab is closed.

![captured2](https://user-images.githubusercontent.com/1475850/38432481-86e67f88-3a02-11e8-9b63-0a69ba91d8f0.gif)

**Comment by mmktomato** [comment]
Oops, mistake.

**Comment by mmktomato** [comment]
Then, this problem happens ONLY when I add many tabs to overflow the tab panel (in other words, scroll bar is shown).

**Comment by Croydon** [comment]
From a technical point of view this is very, very likely the same layout issue as #106.

Again: if someone has good CSS skilly I would appreciate contributions to place the close and mute buttons in a more sophisticated and reliable way.

If I need to do it myself I will need to spend some time to advance my CSS skills and I can't make promises when I can take this time.

**Comment by mmktomato** [comment]
Ok, I understand your situation.

I'd try to fix it when I could take enough time.
But please do not expect because I'm not an expert of CSS 😛

**Comment by Croydon** [comment]
This broke pinned tabs, I will have a look somewhen in the next 48h.

**Comment by Croydon** [comment]
Turned out that this is an unrelated issue.
