### ISSUE TITLE
Dark Theme: Favicon on white background

### ISSUE THREAD

**Issue by xxdavid** [Croydon/vertical-tabs-reloaded#18]
Favicons now have a white background on OS X. Is it intentionally? I think they were transparent but maybe I'm wrong.
![Screenshot](https://cloud.githubusercontent.com/assets/3393339/13860011/984bea04-ec86-11e5-98b3-29ff48190844.png)

**Comment by Croydon** [comment]
This only happens with the dark theme. But I will definitely look into it :)

**Comment by Croydon** [comment]
Addition: You can change the theme in the add-on settings and it is not intentional, at least not from me, no idea what the original author intended.

**Comment by Croydon** [comment]
@xxdavid Will be fixed in v0.4.1.
