### ISSUE TITLE
Can't close tabs by left-click on x (sometines)

### ISSUE THREAD

**Issue by yafp** [Croydon/vertical-tabs-reloaded#188]
Add-on version: 0.10.0
Firefox version: 59.0.2
OS + OS-Version: Ubuntu 16.04
Other tab + user interface related add-ons: none

**Issue**
It's not really reproducible for me so far, but it happens from times to times that i can not longer close tabs via mouse-click. If that happens i can still close tabs via CTRL+W.

**Workaround**
Restarting Firefox solved this issue

**Comment by Croydon** [comment]
What kind of mouse-clicking?

Left click on the X?
Middle click on a tab?
Context menu option?

**Comment by yafp** [comment]
Left click on the X

Haven't tried the other 2 options so far. Will do next time it happens

**Comment by Croydon** [comment]
Might this be related to #177?

**Comment by yafp** [comment]
I dont think so

At least i was not overflowing the tab-bar (no scroll bar needed) when the issue occured, which seems to be different to #177

**Comment by yafp** [comment]
If it happens i get the following output in Firefoxs Browser console:

> TypeError: can't access dead object[Learn More]

from:

>   sidebar.js:266:94

**Comment by Croydon** [comment]
This might be already solved or at least happening fewer times with the current dev version. I will revisit this after the 0.11.0 release.

As a temporary workaround when you run into this problem: Closing and opening the sidebar should "solve" it.

**Comment by yafp** [comment]
i can confirm: your workaround (closing and opening the sidebar) helps.

**Comment by Croydon** [comment]
Please let me know if this still happens with 0.11.0.

**Comment by yafp** [comment]
I'll do

**Comment by Croydon** [comment]
@yafp Is this still something you do encounter?

**Comment by yafp** [comment]
Until now: no.

**Comment by Croydon** [comment]
This might have been related to #194

Closing this because it can't be reproduced anymore.

Please report if you run into this again.
