### ISSUE TITLE
moving tabs between windows confuses VTR

### ISSUE THREAD

**Issue by stevenbagley** [Croydon/vertical-tabs-reloaded#194]
Add-on version: 0.11.0
Firefox version: 60.0.1
OS + OS-Version: Mac OS 10.13.5
Other tab + user interface related add-ons: none

1. Visit a site in Firefox.
2. Open a second Firefox window. Visit a second site.
3. Grab the tab from the tab bar in the second window and move it to the tab bar of the first one.
4. The tab gets merged in, but now VTR will not cycle through that moved tab. Clicking on the X to close in VTR will close the tab, but leave the entry in the VTR panel.

**Comment by Croydon** [comment]
I can't reproduce this anymore with Firefox 61+

@stevenbagley Do you still encounter this problem in up to date Firefox versions?

**Comment by stevenbagley** [comment]
No, problem is gone in Firefox 61. Thanks.
