### ISSUE TITLE
Sometimes pinned tabs are getting hidden

### ISSUE THREAD

**Issue by Croydon** [Croydon/vertical-tabs-reloaded#2]
Perhaps this also happens in the Linux and Mac Themes.

**Comment by yafp** [comment]
You you mean the pinned tab isn't visible at all?
Or that it looks like a normal tab?

**Comment by Croydon** [comment]
Right, it was not visible anymore at all. However, I have not experienced this bug in a long time. So it may be already fixed or was never a bug in a released version or something.

I will close it soon if nobody will report something like that.

**Comment by Croydon** [comment]
This seems to happening randomly with all themes.
Pinned tabs are getting out of the scrollable area.

**Comment by autra** [comment]
FWIW, I'm reproducing it pretty consistently. Firefox stable on Ubuntu 16.04. My pinned tab disappears when I scroll the tablist. 

*Expected*

Pinned tabs area stays on top when scrolling the list of tabs.

*actual*

Pinned tabs are in the tab scrollable areas, meaning that when I scroll down, they disappear.

**Comment by retep998** [comment]
I can reproduce this consistently on Windows. I open enough tabs so a scroll bar appears, I pin some tabs, and if I scroll down, I can only scroll up enough so that the first non-pinned tab appears. I cannot scroll up enough to have the pinned tabs visible again. The issue only applies when using the scroll wheel. If I click and drag the scroll bar it works fine.

**Comment by unknown--** [comment]
Sad to see this issue has lived on throughout each fork. It's really the only reason I've never used the tab pin feature.

**Comment by dexter777** [comment]
Will this be fixed in some near future? I just tried this extension and this is really annoying as I have few tabs pinned and usually 40-80 other tabs open, it's kinda annoying that using mouse scroll to scroll tabs list stops right before pinned tabs

**Comment by Croydon** [comment]
@dexter777 Right now the only priority is porting VTR to a WebExtension. See #13 
All old code will stop working in November. Investing time into the current code base is just a waste of time and in specific I'm expecting fixing this bug is heavily time consuming. 

Not sure if I will fix this bug on-the-fly while porting but at least afterwards bugs like this will be the priority.

Given the nature that porting is not yet fully possible, it's really hard to say when something like this will land. More people should tell Mozilla that their time management is a disaster.

**Comment by Croydon** [comment]
Fixed with bc3b43ec6ce6a6ac10dcb4e5362f9d95fcc7a7cf.

Will still take some time till this lands as a stable feature in a stable VTR version. More info at #13

#13 will also fix it that pinned tabs get sometimes randomly closed.
