### ISSUE TITLE
FR: Click active tab to jump to last active tab

### ISSUE THREAD

**Issue by polyzen** [Croydon/vertical-tabs-reloaded#200]
There's an extension named [Tab flip](https://framagit.org/ariasuni/tst-tabflip) that adds this feature to TST. It also adds a ctrl+shift+space shortcut for this.

Thank you for this great extension.

**Comment by Croydon** [comment]
I'm unsure about this one.

@polyzen Could you please give more context to this feature request? In which common cases in this useful?

**Comment by polyzen** [comment]
I now just use the `ctrl-6` binding provided by the Tridactyl extension to jump to the previously active tab. It's great for jumping back-and-forth between tabs.

**Comment by Croydon** [comment]
I'm closing this as `wontfix` as this functionality can be easily added via shortcuts and it isn't directly connected to vertical tabs
