### ISSUE TITLE
[Feature Request] Additional option to show ALL pinned tabs in sidebar

### ISSUE THREAD

**Issue by AndyL964** [Croydon/vertical-tabs-reloaded#206]
Add-on version: 0.11.0
Firefox version: 63.0 (64-Bit) Beta
OS + OS-Version: Windows 10 1803
Other tab + user interface related add-ons: N/A

Feature request for an option in add-on settings which you can enable/disable to show pinned tabs from every window that is currently open in Firefox. This helps to relieve the hassle of having to switch between windows just to check out the pinned tabs, especially if, for example, you like to have a lot of YouTube videos opened in the background playing music as you browse the internet.

**Comment by Croydon** [comment]
I understand your use case and could use this sometimes as well.

However, this is a major hijacking in how pinned tabs are working in Firefox and I fear this could open Pandora's Box when it comes to re-defining behaviour. 

I will need to think about that for a while and also would like to hear if other users could need this.

**Comment by Croydon** [comment]
I'm sorry, but I'm not going to implement this.

I don't want to hijack the tab information I'm getting and/or sending to Firefox too much. This is just too error-prone and costs too much time for too little outcome.

Hypothetically, even if I would implement that all pinned tabs from all windows would get displayed in every single window you would still switch the focused window as soon as you are clicking on a pinned tab from another window, which cuts the benefit of such a feature in half as you would still need to manually navigate back to our former focused window.
