### ISSUE TITLE
Ctrl+Tab jumps to arbitrary tab

### ISSUE THREAD

**Issue by HeRo002** [Croydon/vertical-tabs-reloaded#207]
Hi

I couldn't find any existing bug report on this: 

When I press Ctrl+Tab or Ctrl+Shift+Tab focus jumps to an arbitrary tab (in the same tab group). 
Sometimes there is some logic to which tab these 2 key combinations jump to. Other times I really can't see the system. 
I also use Simple Tab Groups, so it might be some kind of incompatibility between the two. 

Add-on version: 0.11.0
Firefox version: 62.0.3 (64-bit)
OS + OS-Version: Ubuntu 18.04.1 LTS (with Gnome 3.28.2)
Other tab + user interface related add-ons: Simple Tab groups 3.2.1

**Comment by grahamperrin** [comment]
Is this reproducible with developer version 0.12.0a6? From https://addons.mozilla.org/addon/vtr-developer-version/

Hint: before installing or enabling the developer version, disable the release version.

**Comment by yafp** [comment]
@grahamperrin 
issue seems fixed with the developer version (0.12.0a6)

**Comment by Croydon** [comment]
I can neither reproduce this problem with 0.11.0 nor with 0.12.0a8.

@HeRo002 Do you still experience this issue? If yes, please test it with 0.12.0 which I will release next week.

**Comment by Croydon** [comment]
Closing as @yafp reports that it is fixed, @HeRo002 is not reporting back and I could never reproduce this.
