### ISSUE TITLE
Toolbar stops working after position set to top and FF restarted

### ISSUE THREAD

**Issue by jimmyjudas** [Croydon/vertical-tabs-reloaded#212]
In VTR options, set toolbar position to Top. Toolbar moves to top and works as expected. Restart firefox. Toolbar now shown at bottom (despite setting still showing "Top") and neither the new tab button or the options button work. Changing position in the options does change the tab position but doesn't make the buttons work - the only way to fix it is to set the position to Bottom and restart firefox.

Add-on version: 0.11.0
Firefox version: 63.0.3 (64-bit)
OS + OS-Version: Windows 10, 1709
Other tab + user interface related add-ons: Multiple Tab Handler, Rename Tab Title, Tab Session Manager, Undo Close Tab

**Comment by Croydon** [comment]
0.12.0 is now released. Please update and check it again :)

**Comment by jimmyjudas** [comment]
The click actions now work just fine, thanks! However, the toolbar now appears at the top after a restart, even if I've selected the bottom option. I want it at the top so not a problem for me, but just thought you'd want to know!

**Comment by Croydon** [comment]
Thanks for reporting this! Will be fixed soon 😄
