### ISSUE TITLE
favicons for discarded tabs

### ISSUE THREAD

**Issue by milkmiruku** [Croydon/vertical-tabs-reloaded#221]
Add-on version: 0.12.1
Firefox version: 64
OS + OS-Version: Arch Linux

Discarded tabs don't get their own favicons, they get greyscale globes.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/discard

https://addons.mozilla.org/en-GB/firefox/addon/auto-tab-discard/

https://github.com/rNeomy/auto-tab-discard

**Comment by Croydon** [comment]
This is a Firefox problem, see e.g.

https://bugzilla.mozilla.org/show_bug.cgi?id=1450382
https://bugzilla.mozilla.org/show_bug.cgi?id=1427822

**Comment by Croydon** [comment]
Also: 

https://bugzilla.mozilla.org/show_bug.cgi?id=1315616

**Comment by milkmiruku** [comment]
Thanks for the information! Maybe this issue could count as a request for a workaround, as Auto Tab Discard appears to have, though no worries, I guess the fix will trickle down eventually anyway.

**Comment by milkmiruku** [comment]
Ah, no! Newly discarded tabs don't lose their icon :)
