### ISSUE TITLE
Tooltips stuck after switching to other app

### ISSUE THREAD

**Issue by brondsem** [Croydon/vertical-tabs-reloaded#227]
Add-on version: 0.12.1
Firefox version: 65.0.1
OS + OS-Version: macOS 10.14.3
Other tab + user interface related add-ons: 

If a tab tooltip is showing, and then I cmd-tab to switch applications, the tooltip continues to display in front of all windows from all apps.  Its still there even when I switch back to Firefox, until I hover on the sidebar tabs again.

A "Close tab" tooltip can get stuck without even switching apps.  If I move the cursor quickly enough from a tab, to the right past the "X", then "Close tab" will stay there even when my cursor is on the main webpage area.

**Comment by Croydon** [comment]
Just to double check: You are actually meaning the tooltips, not the context menu of tabs? Tooltips would be the tab title, tab url and "Close tab".

If it is the tooltips, then there is nothing I can do. These are default HTML attributes, if they don't get hidden in certain situations than it is a Firefox bug.

**Comment by brondsem** [comment]
Yes, tooltips.  I tested with bookmark tooltips as a comparison and they don't have this problem, either in a top bookmark menu or with the bookmark sidebar (same area vertical tabs use)

**Comment by brondsem** [comment]
Weird, I also tried moving the sidebar to the right, and then the problem stopped.  I moved the sidebar back to the left and the problem is still gone.  So yeah maybe some Firefox bug and swapping the sidebar around cleared up whatever was bugging it.

**Comment by Croydon** [comment]
Closing as I'm pretty sure that I can't change the behaviour of this.

**Comment by 29988122** [comment]
Same Firefox bug.

Just want to confirm that swapping it left and right works for me.

**Comment by Croydon** [comment]
Just to have this documented somewhere: Yes, this was a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=148624

**Comment by 29988122** [comment]
> Just to have this documented somewhere: Yes, this was a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=148624

Nice to see you back! : D
No other intentions, just wanna let you know that I'm still using it everyday, and it benefits me a lot!
