### ISSUE TITLE
Scrolling vertical tabs

### ISSUE THREAD

**Issue by hfrictionless** [Croydon/vertical-tabs-reloaded#23]
Scrolling in vertical tabs sidebar changes the viewed tab. Is it possible to just scroll the content of the sidebar?

**Comment by Croydon** [comment]
I can't reproduce this error. Anybody else with this problem?

@hfrictionless Could you please try to disable temporary all other add-ons and restart afterwards Firefox once to see if the error is persistent?

**Comment by woj-tek** [comment]
For me scrolling on the tab-bar (on the right) causes change in the active tab... but for this is expected behaviour - majority (all?) applications changes the tab while scrolling over the tab-bar (be that vertical/horizontal)

**Comment by Croydon** [comment]
This issue is very likely a duplicate of #47 and therefore a Firefox bug.
@hfrictionless do you use a trackpad?
@woj-tek Do you use also a trackpad when reproducing this?

**Comment by woj-tek** [comment]
Not only - this happens both with trackpad and mouse scroll, and *for me* it's desired and I find it *very useful* :-)

**Comment by Luckz** [comment]
There are extensions that add this behaviour (the mouse wheel scrolling tab selection), does it happen with this addon alone?

**Comment by Croydon** [comment]
Closing as duplicate of #47. Might be fixed by Firefox 49 and newer by now.
