### ISSUE TITLE
Context menu hidden behind the default context menu

### ISSUE THREAD

**Issue by Mr-Personality** [Croydon/vertical-tabs-reloaded#231]
If **dom.event.contextmenu.enabled** is set to false, it breaks the context menu for Vertical Tabs Reloaded - the default Firefox context menu appears in front of the other one and completely hides it

I didn't even know that Vertical Tabs Reloaded _had_ its own context menu until I found that I wasn't able to bookmark tabs, so started investigating the missing button.

I have no intention of enabling **dom.event.contextmenu.enabled** because I believe a web browser's context menu is a fundamental part of the program that websites should never be allowed to mess with. In my opinion, letting websites mess with the context menu is grossly overcomplicating the web and presenting a needless security risk.

Add-on version: 0.12.1
Firefox version: 66.0.5
OS + OS-Version: Windows 7 64 bit
Other tab + user interface related add-ons: Max Tabs

**Comment by Croydon** [comment]
This will be solved with #205
