### ISSUE TITLE
Automatically toggle between top tabs and vertical tabs

### ISSUE THREAD

**Issue by tobia** [Croydon/vertical-tabs-reloaded#232]
Is it technically possible to have a button / hotkey toggle between Firefox's default horizontal tabs and the vertical tabs? Meaning hiding one and showing the other, without having both visible, and without restarting Firefox.

If it's possible, then we could have an automatic rule, to hide the top tabs and show the vertical ones depending on the window width and number of open tabs.

**Comment by Croydon** [comment]
To quote the "About this extension" section (https://addons.mozilla.org/en-US/firefox/addon/vertical-tabs-reloaded/):

> The default horizontal tab browser can't be hidden right now, that's a limitation in Firefox itself:
https://bugzilla.mozilla.org/show_bug.cgi?id=1332447
