### ISSUE TITLE
userChrome.css data not controling VTR UI like it supposed to.

### ISSUE THREAD

**Issue by ketonik** [Croydon/vertical-tabs-reloaded#233]
Add-on version: 0.12.1
Firefox version: 69
OS + OS-Version: 10.4.4
Other tab + user interface related add-ons: 

userChrome.css  supposed to control FireFox UI
userContent.css supposed to control Page Content

This is not the case with VTR, font type and size values specified in userChrome.css  have no affect on the tab text font/size.

If the same data is added to userContent.css and the preference "Allow pages to choose their own fonts, instead of your selections above"
is checked in:

Preferences>Fonts>Advanced

It will control the VTR Tab text font type/size.

That ain't cool and totally confusing people thinking FF Quantum has switched 
userContent.css to control FireFox UI
userChrome.css to control Page Content

**Comment by Croydon** [comment]
I'm sorry, but modifications through `userChrome.css` are a complete wildcard that I can't support.

If you really want to do this, you need to have a look at the internal add-on structure and how VTR templates are using CSS variables. If you overwrite the value of certain CSS variables you should be able to get to your goal.

But again, I can't provide support for this.

Changing the font size will be eventually a feature. Follow #195 for progress
