### ISSUE TITLE
Drag to bookmark

### ISSUE THREAD

**Issue by jzakula** [Croydon/vertical-tabs-reloaded#235]
Hi,
I love the addon - much cleaner than tree tabs. I just installed it and have sent a donation.
I have 1 feature suggestion. I used userChrome.css to eliminate the the builtin tab bar. Now, if one could drag a tab to a bookmark folder, this would indeed be a killer app!
Thanks for the good work,
Jeff

**Comment by Croydon** [comment]
Hi @jzakula!

Thanks for using VTR and for the donation! 😄 

Progress on this issue is tracked in #140 and in fact, it is already implemented. The next release of VTR will have this feature
