### ISSUE TITLE
No longer able to move tabs

### ISSUE THREAD

**Issue by cfdude** [Croydon/vertical-tabs-reloaded#236]
Add-on version: 12.1
Firefox version: 70.0.1
OS + OS-Version: Mac OS Mojave
Other tab + user interface related add-ons: Auto Tab Discard

Seems like in this version I can no longer click (hold) and drag tabs to move them.  They are stuck.

**Comment by Croydon** [comment]
What do you mean with "this version"? 
Did you update your VTR version or your Firefox version? 
What version did you use previously?

**Comment by cfdude** [comment]
nevermind, I just restarted Firefox and it's working again
