### ISSUE TITLE
shortcut 

### ISSUE THREAD

**Issue by emacsomancer** [Croydon/vertical-tabs-reloaded#237]
Add-on version: latest
Firefox version: latest
OS + OS-Version: linux 5.4.21
Other tab + user interface related add-ons: none

Every time I close and re-open Firefox, the short-cut key to open the tab list resets to the default value.

**Comment by Croydon** [comment]
What shortcut value are you trying to set?

**Comment by emacsomancer** [comment]
In "Add Ons" menu, "Manage Extension Shortcuts": Vertical Tabs Reloaded: "Hotkey for showing/hiding the tab sidebar"

**Comment by Croydon** [comment]
Could you please try to set it through the add-on settings itself? Addons -> Vertical Tabs Reloaded -> Options

The global addon shortcut page is new and maybe VTR conflicts with it right now

**Comment by emacsomancer** [comment]
Ah, I didn't realise that. I'll try setting it there.
