### ISSUE TITLE
Stop working in combination with hidden tabs(Simple Tabs Group)

### ISSUE THREAD

**Issue by 29988122** [Croydon/vertical-tabs-reloaded#246]
Add-on version: 0.13.0
Firefox version: 75.0
OS + OS-Version: Windows 10
Other tab + user interface related add-ons: 
Simple Tabs Group

***

Basically, as title.
New fonts and sizes:
![圖片](https://user-images.githubusercontent.com/5474709/79759647-87134c80-8351-11ea-9e85-a03aaf7d2af9.png)
Very ugly and unnecessary even after firefox restart.

The previous visual and compactness is more pleasing:
![圖片](https://user-images.githubusercontent.com/5474709/79759747-a8743880-8351-11ea-865d-72ce15a5bcf4.png)

And if you compare them side by side with the same sizes:
![圖片](https://user-images.githubusercontent.com/5474709/79761749-731d1a00-8354-11ea-99e5-e362e65f31eb.png)

Another one with grid lined up:
![圖片](https://user-images.githubusercontent.com/5474709/79761773-79ab9180-8354-11ea-8f9a-3a8b250bcedb.png)

Please revert this change, or at least give us an option for it.
Thanks!
***
It also stop working, together with Simple Tabs Group.
Not showing tabs correctly anymore, now VTR's showing "all the tabs" in Firefox, not the ones (container?) by Simple Tabs Group correctly.

If the abovementioned bug can be fixed, I'd be verry happy!
Thank you for your development.

**Comment by Croydon** [comment]
For future issue filling: Please don't combine unrelated problems into one issue. Thanks! 😄 

The increased font size is on purpose as many complained that it is too small. However, I will add an option in the future to configure that. Please follow #195 

_________________

For the tab hiding / tab group part:

1) Can you reproduce this problem? Is the problem still there if you a) close and re-open the sidebar? b) Close and re-open Firefox?

2) Are the tabs shown vertical identical to the tabs shown in the horizontal bar?

**Comment by Croydon** [comment]
I think I found the problem. 

Would you be willing to install the developer version for a test to see if this fixes the problem for you? You can remove this version again after a test 

https://croydon.github.io/vtr-releases/

**Comment by 29988122** [comment]
1. I can confirm that 
![圖片](https://user-images.githubusercontent.com/5474709/79778824-f26a1800-836b-11ea-954e-95bf0490a9ce.png)
the bug's been fixed in the dev build. 

Thank you Mr.Croydon!

2. I'm looking forward to your https://github.com/Croydon/vertical-tabs-reloaded/issues/195 future work! 
![圖片](https://user-images.githubusercontent.com/5474709/79778681-bb940200-836b-11ea-85e8-5ec9a62f54a4.png)
As you can see I got tons of tabs...and trust me, those are all ongoing side-projects. (archived/low priority ones are in the bookmark folder)

By adding appearance options, this will be ideal for everyone. In the meantime, I guess I can fork and revert the css change on my side. Thank you for this is awesome opensource project!

**Comment by jonafato** [comment]
@Croydon I can also confirm the tab-hiding issue and the fact that it's fixed in the development release you've linked. Thanks for fixing the issue so quickly!

**Comment by duncanawoods** [comment]
> The increased font size is on purpose as many complained that it is too small. However, I will add an option in the future to configure that.

I can confirm that it is unbearable. Can you revert it and defer the larger size for the future when you have that feature please?

**Comment by Croydon** [comment]
0.13.1 is released with a fix for tab hiding

Font size -> #195
