### ISSUE TITLE
Left/right position Window-local

### ISSUE THREAD

**Issue by Da-kota** [Croydon/vertical-tabs-reloaded#248]
Add-on version: 0.13.0
Firefox version: 75.0
OS + OS-Version: Ubuntu 16.04 LTS
Other tab + user interface related add-ons: 

Would love to be able to move sidebar to left or right independent of other windows.

**Comment by Croydon** [comment]
Sorry, this is out of my hands.

The (empty) sidebar itself and its position is a Firefox feature. You will need to ask Firefox to implement this

**Comment by Da-kota** [comment]
Ah,  I overlooked that,  I could have known.  Sorry and thank for the great work.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
