### ISSUE TITLE
Tooltip sticks around forever even when switching windows (OSX)

### ISSUE THREAD

**Issue by mathieulb** [Croydon/vertical-tabs-reloaded#249]
Add-on version: 0.13.1
Firefox version: 77 (and several previous)
OS + OS-Version: OSX 10.15.5
Other tab + user interface related add-ons: 3 lines in userChrome.css for hiding sidebar header & hiding firefox's tabs

Hovering on any toolbar item causes a tooltip to appear even after hovering out of the sidebar, and even after switching to different windows of Firefox, and even when switching to other apps. Then it sticks around forever until coming back to the sidebar of *that* window. The only way to stop displaying a tooltip for something in the VTR of that window is to put the (mouse) cursor on an unused area of VTR before moving the cursor to web content or before Cmd+tab or Cmd+backtick. If the whole height of VTR is filled, the only unused space is to the right of the sprocket icon. And if the sidebar is on the right, then after hovering that blank space, the cursor must go up, left then down in order to reach web content, going around the sprocket and "plus" icons, because those two also have tooltips with the same problem. All this to say that it's a fairly annoying bug :-D

**Comment by Croydon** [comment]
HI @mathieulb!

It has been a minute, sorry for that. I don't have access to macOS and I can't replicate your problem on any other configuration.

Is this still a problem for you with a current version of Firefox?

**Comment by Croydon** [comment]
Just to have this documented somewhere: Yes, this was a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=148624#c42
