### ISSUE TITLE
Feature request: Send tab to device in contextmenu

### ISSUE THREAD

**Issue by steampunklolcat** [Croydon/vertical-tabs-reloaded#257]
Would it be possible to add the "Send to device" feature to the contextmenu of the addon?

Right now I have to go to the built-in horizontal tab-bar to access it from the contextmenu there.

Add-on version: 0.13.1
Firefox version: 86
OS + OS-Version: MacOS Big Sur 11.2.2

**Comment by Croydon** [comment]
Unfortunately, this is currently impossible. For tracking this feature, there is issue #178
