### ISSUE TITLE
An option for behavior after startup

### ISSUE THREAD

**Issue by Amad22** [Croydon/vertical-tabs-reloaded#260]
Add-on version: 0.13.1
Firefox version: 91 ESR
OS + OS-Version: Win10-64 Home 21H2
Other tab + user interface related add-ons: CustomCssForFX

Hello
Thank you for useful addon and for nice dark theme. 
I use FF in mode that I have opened several windows (each FF window contain tabs from one theme (general, work, ware...) for reason to lower amount of tabs in one FF window. When I fully shutdown or restart PC, the FF opens all windows again. But the VTR appears in each windows and I need close each VTR manually after each PC restart or full schutdown. Especially it is bother when I use monitor in portrait mode, when the screen width is narrow without VTR yet. (I do not use VTR all time, only sometimes for special situation (to rearange the order of opened tabs; it is easy due to vertical look)). 
So could not be added an settings option for VTR state after FF startup? I think I am not only who would invite it.

**Comment by Croydon** [comment]
Thank you for your feedback, but this is impossible to implement on my behalf.

Add-ons can't open or close the sidebar without explicit user action, meaning I can't implement any kind of logic when it should be open or closed.

Firefox itself does not remember the status of sidebars (open/closed) per window, but just what the last user action in any window was. If your last action was to open the sidebar in one window, close Firefox and re-open it, the sidebar will be opened in all windows again. 

Similarly, if your last action is to close the sidebar in one window, close Firefox and re-open it, the sidebar won't be opened in any window.

I understand the need for your request, but there is nothing I can do here, sorry.
