### ISSUE TITLE
Undesired duplication/proliferation of tabs

### ISSUE THREAD

**Issue by Ted-Egan** [Croydon/vertical-tabs-reloaded#261]
Add-on version: 0.13.1
Firefox version: 91.4.1esr (64-bit)
OS + OS-Version: Win 10 Home v. 21H1 Build: 19043.1415
Other tab + user interface related add-ons: 

I searched but did not find this as an open issue.

VTR appears to have an issue that occurs after a certain number of tabs have been opened.  I have not tried to determine what the magic number is.

The issue is that VTR starts duplicating tabs on its own initiative.  I believe VTR is sometimes doing this without any user input at all.  But it also happens frequently when I click on a tab, especially one that has been open or in existence for some time.  VTR will open a new tab, located not directly under or following the one I clicked, but instead under the one *under* the one I clicked.  Then it will open the page or site already open in the tab that I clicked.  I must do a huge amount of housekeeping to keep nuking these undesired duplicated tabs.  The fact that I often do not see these tab duplicates opening up, but instead, later on, see that I have duplicates up and down the column of tabs, is what leads me to believe that this tab duplication is happening due to causes other than my merely clicking on an extant tab.

**Comment by Croydon** [comment]
I have almost always 1000+ tabs open in a single window and have Firefox running for hours. I never encountered this problem. I also can't think of anything within VTR that could cause this problem. Not sure if I can do anything here without further information 🤔

**Comment by Croydon** [comment]
Please provide more information if this is still a thing. Closing as not reproducible for now.
