### ISSUE TITLE
Doesn't show up in a private window on MacOS, despite permission given

### ISSUE THREAD

**Issue by mathieulb** [Croydon/vertical-tabs-reloaded#263]
Add-on version: 0.13.1
Firefox version: 98.0.2 (and since a long time)
OS + OS-Version: MacOS 12.3
Other tab + user interface related add-ons: none

VTR doesn't show up in a private window on MacOS, despite permission given.

But the same thing works for me on Linux.

**Comment by Croydon** [comment]
Maybe it is closed by default.

Did you actually try to open the sidebar? If so how? Did you use the button? The hotkey?

**Comment by mathieulb** [comment]
Right, sorry, false alarm :-( It's off by default, that's all, and I don't know why I went this far without realising. It's much quicker to press Cmd+shift+v than to file a bug report about a non-bug AND then having to press Cmd+shift+v nonetheless.
