### ISSUE TITLE
request for HORIZONTAL tabs on the bottom of the screen

### ISSUE THREAD

**Issue by gg2by2** [Croydon/vertical-tabs-reloaded#264]
hello, 
this is not an issue with vertical tabs reloaded. i thought if you could write code to stack the tabs vertically, perhaps you could
write an addon to locate the tab bar at the bottom of the screen, just above the taskbar. 

there are a lot of us old timers who miss the old arrangement. there was a addon, "Tabmix plus" that could do that only with ff versions 50+.

**Comment by Croydon** [comment]
I don't think this is possible in a sophisticated, stable way. 

VTR uses the vertical sidebar API that Firefox provides, but no horizontal toolbar API exists (https://bugzilla.mozilla.org/show_bug.cgi?id=1215064). 

The only way to implement this would be to inject a tab bar into every single website you visit. This is a horrible idea for several reasons:
  * it can break websites
  * websites can break the tab bar, meaning it is not reliable
  * it does not work in "privileged tabs" (Firefox settings tabs, add-on tab, local file tabs....)
  * it is a privacy and security disaster as websites could potentially mess with the tab bar

Additional, this is out of scope of VTR, sorry.
