### ISSUE TITLE
Context menu items are removed

### ISSUE THREAD

**Issue by Keith94** [Croydon/vertical-tabs-reloaded#27]
In the toolbar context menu, the "Move to Menu" and "Remove from Toolbar" items are not available:

![snag 2016 03 27 01 02 02](https://cloud.githubusercontent.com/assets/5490615/14064454/957d232c-f3b8-11e5-9e9c-54bc301c271f.png)

Expected behavior:

![snag 2016 03 27 01 01 19](https://cloud.githubusercontent.com/assets/5490615/14064458/9bfe2c14-f3b8-11e5-97a4-1c594fe4a50c.png)

**Comment by Croydon** [comment]
Will be fixed with the next update. Thanks for reporting.
