### ISSUE TITLE
This extension hides the right-click context menu entries for other extensions

### ISSUE THREAD

**Issue by venteto** [Croydon/vertical-tabs-reloaded#271]
Add-on version: 0.13.1
Firefox version: 109 (64 bit)
OS + OS-Version: Manjaro Linux 22.0.0 Sikaris
Other tab + user interface related add-ons: 
* Firefox Multi-Account Containers
* [Simple Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/)
* [UnloadTabs](https://addons.mozilla.org/en-US/firefox/addon/unload-tabs/)

(I also have the horizontal tab bar hidden via a custom Firefox stylesheet.)

I like Vertical Tabs Reloaded but I disabled it because I cannot access the UnloadTabs context menu when using it, and I use the "unload other tabs" context menu entry often.

It also hides the context menu entries or the Simple Tab Groups extension, so I cannot right-click on a tab and send it to another tab group.

I tried using the [Vertical Tabs](https://addons.mozilla.org/en-US/firefox/addon/vertical-tabs/) extension instead, as it does not hide UnloadTabs context menu entries when right-clicking (secondary-clicking) on individual tabs. Unfortunately, Vertical Tabs seems slower than Vertical Tabs Reloaded, and I'm pretty sure a couple of months ago I stopped using Vertical Tabs because it seemed to make me lose a lot of tabs in multiple tab groups (as grouped by the [Simple Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/) extension). Moreover, now Vertical Tabs [seems to be unmaintained](https://github.com/typeling1578/vertical-tabs).

Vertical Tabs Reloaded would be my ideal implementation of a vertical tab extension if I could access the UnloadTabs menu, and never lose any of my tab groups. I also tried using [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/), which didn't seem to corrupt my tab groups, nor hide the UnloadTabs context menu. However I don't want my tabs in trees, I just don't like that behavior. I want new tabs to just go right next to the tab I am currently in, and I don't want trees being collapsed, particularly if I am unaware of it. Additionally, [Sidebery](https://addons.mozilla.org/en-US/firefox/addon/sidebery/) is trying to be too many things, all I want is a vertical tab extension, not something also combining, e.g., the bookmarks menu.

**Comment by Croydon** [comment]
While what you describe is correct, technically speaking, VTR is not hiding any entries, it is implementing a completely new context menu, because it wasn't possible at the time.

This will be eventually solved by #205
