### ISSUE TITLE
Gap between tabs

### ISSUE THREAD

**Issue by mbaz** [Croydon/vertical-tabs-reloaded#29]
I'm getting some blank, inactive space between tabs. Screenshot here: http://imgur.com/uLWzjRG

To reproduce, just close some tabs in the middle of the list. The tabs below do not "slide up" and a gap is created where the blank tab used to be.

Running 0.4.0 on Firefox 45, Arch Linux.

**Comment by Croydon** [comment]
Please use the search before reporting issues.

Duplicate of #14.

**Comment by mbaz** [comment]
Sorry -- I did search, but somehow missed it.
