### ISSUE TITLE
Addon icon/logo

### ISSUE THREAD

**Issue by Croydon** [Croydon/vertical-tabs-reloaded#3]
I'm open for all kind of suggestions :)

**Comment by yafp** [comment]
Hi, 
got 0.3.2 running right now - is it on purpose that the icon contains the string VRT - while the addon itself is called 'vertical tabs reloaded' -> VTR might fit better ;)

**Comment by Croydon** [comment]
Ooops, indeed, seems like a lot of embarrassing stuff can happening if you are trying to be productive while tired. 😅
Will be fixed. Thanks.

**Comment by yafp** [comment]
;)
