### ISSUE TITLE
"dead space" when closing tabs

### ISSUE THREAD

**Issue by Marty** [Croydon/vertical-tabs-reloaded#31]
This just started happening, so I assume it has to do with the latest update:

**Problem:**
The space of the first three tabs that I close is not freed up.
This leaves me with an annoying gap between my tabs.

![vertical-tabs-bug](https://cloud.githubusercontent.com/assets/100658/14109747/d8f8970a-f5c3-11e5-9cfb-2379b9ebcca9.jpg)

**How to reproduce:**
Open a new window, open 4+ tabs, close the 3 top ones.

Happens with all themes on Firefox 45.0.1

**Comment by Croydon** [comment]
Please use the search before reporting issues.

Duplicate of #14.
