### ISSUE TITLE
Compatibility with Fast Dial add-on

### ISSUE THREAD

**Issue by yafp** [Croydon/vertical-tabs-reloaded#36]
Since 0.5.0 i had a strange issue on 1 (fedora 23, 65 bit) of my machines.
From times to times it seems like the addon is not working after starting my browser.

In this case the last session is gone as well and the tabs are on top.
The addon preferences are displayed incomplete as well.
Its really a strange bug i cant manually reproduce, but it happens several times now.

Screenshots
![20160403_00 10 33_add-ons-manager - mozilla firefox_001](https://cloud.githubusercontent.com/assets/67605/14232135/6ff7e736-f99e-11e5-8675-e46ce2fb06aa.png)
![20160403_00 10 18_add-ons-manager - mozilla firefox_001](https://cloud.githubusercontent.com/assets/67605/14232136/6ffcb5a4-f99e-11e5-8035-4164f881b07d.png)

**Comment by Croydon** [comment]
Have you looked into the Browserconsole (not Webconsole!) to look for some possible error message when this is happening?

**Comment by yafp** [comment]
you mean CTRL+SHIFT+J?

Not yet, but gonna do so the next time this happens

**Comment by Croydon** [comment]
That is exactly what I mean :)

**Comment by yafp** [comment]
Seems like it might be a side-effect with another plugin vallied "Fast Dial". Still investigating.....

**Comment by Croydon** [comment]
@yafp Could you find the source of the problem?

**Comment by yafp** [comment]
not 100% sure - i had the impression the issue come after upgrading to 0.5.0 and might be related with the Fast Dial addon.

I removed Fast dial from my addon list and the issue is gone since then

**Comment by Croydon** [comment]
I accidently closed this by writing the wrong issue number in a commit.

**Comment by Croydon** [comment]
@yafp What is the advantage of Fast Dial in comparison to the default Firefox tiles anway?

**Comment by yafp** [comment]
@Croydon 
The amount of tiles (i.e. 10 x 8) is configurable and they are fully user-configured (not based on some kind of automatism

**Comment by Croydon** [comment]
@yafp Since Fast Dial add-on has a huge amount of users I am willing to investigate further, but I definitely need more information what exactly is not working when both add-ons are installed.

**Comment by Croydon** [comment]
I consider the advantages of this add-on as too small. Sorry, for anyone who wants to use Fast Dial + VTR.
If Fast Dial is getting rewritten as a WebExtension they should definitely not anylonger interfere each other, if not then it will stop working at the end of 2017.
