### ISSUE TITLE
Not working when starting in Private Browsing mode.

### ISSUE THREAD

**Issue by danwep** [Croydon/vertical-tabs-reloaded#41]
Add-on version: 0.6.1
Firefox version: 46.0.1
OS + OS-Version: Linux, Debian testing[codename stretch]

Vertical Tabs Reloaded[VTR], does not work when starting Firefox in private
browsing mode.

After starting Firefox in private browsing mode and opening new windows
of any type and VTR, does work correctly on these new windows. The only
add-on installed was VTR, in a new profile to avoid any conflicts with
other add-ons and/or user settings.

The following is the error once Firefox quits:

```
$ firefox -no-remote -private-window -P debugging
console.error: vertical-tabs-reloaded:
  Message: TypeError: GLOBAL_SCOPE[("vt" + windowID)] is undefined
  Stack:
    exports.main/<@resource://gre/modules/commonjs/toolkit/loader.js -> resource://verticaltabsreloaded-at-go-dev-dot-de/index.js:123:3
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
windowEmit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/windows/firefox.js:175:41
windowEventListener@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/windows/firefox.js:208:29
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:123:45
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
initialize/<.onUntrack@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/windows/observer.js:28:9
_unregWindow@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/deprecated/window-utils.js:112:9
observe@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/deprecated/window-utils.js:153:7

```

Thank You for this add-on, which just found recently. Much better than
others that have tried in the past and not having tree style tabs.

**Comment by Croydon** [comment]
This turned out to be a Firefox bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1248903
https://bugzilla.mozilla.org/show_bug.cgi?id=1196577

I will try to make some noise about this bug, but there isn't anything I can do beyond that.

**Comment by danwep** [comment]
Ok, and Thank You for the links.

**Comment by Croydon** [comment]
I guess Mozilla won't invest anymore resources to work on the add-on SDK even it's about fixing stuff. At the end of 2017 only WebExtensions will work anyway.

I have started to work on porting this add-on step-by-step to a WebExtension. You can follow this work at #13.

I will leave this bug open for a while so that people don't report this even more often.

**Comment by Croydon** [comment]
Not that I would complain, but for some completely unknown reason this bug is gone.

Maybe Mozilla did refactor some code parts and fixed this bug without knowing it, either way: 🎉🎉🎉

**Comment by Croydon** [comment]
@danwep If you are still around it would be nice if you could verify this :)

**Comment by danwep** [comment]
@Croydon 

Can confirm, this is no longer an issue. Thank You :)
