### ISSUE TITLE
Tab drag&drop fails past the current visible tabs

### ISSUE THREAD

**Issue by danwep** [Croydon/vertical-tabs-reloaded#43]
Add-on version: 0.6.1
Firefox version: 46.0.1
OS + OS-Version: Linux, Debian testing[codename stretch]

Can not move tabs past the current visible tabs. Either by going up the
tabs or down. Also when disabling VTR, and trying to move tabs; they
will only move to tab position number 1, when moving from right to
left[backwards] and tab position number 9, when moving from left to
right[forwards]. The only add-on installed was VTR, in a new profile
to avoid any conflicts with other add-ons and/or user settings.

Thank You for this add-on, which just found recently. Much better than
others that have tried in the past and not having tree style tabs.

**Comment by Croydon** [comment]
Tab moving after disabling VTR fails due to #8.

The general tab moving problem hasn't been reported till now, thank you.

**Comment by fb87** [comment]
While dragging a tab, scrolling with the mouse wheel isn't possible. By resolving this issue, please don't affect trackpad behaviour.

**Comment by Croydon** [comment]
Will be fixed somewhen, somehow with #13.

**Comment by Croydon** [comment]
Actually this is not a problem for me anymore.
@danwep @fbruetting Mind to retest with v0.8.3?

**Comment by fbruetting** [comment]
Not necessary, Mozilla already provides vertical tabs as an Extension.

**Comment by Croydon** [comment]
Tab Center is an experiment from Mozilla which will very likely stop working with FF57 in Nov.

**Comment by Croydon** [comment]
Actually seems like it will stop working in August.

https://github.com/bwinton/TabCenter/pull/1082#issuecomment-300866329

**Comment by fbruetting** [comment]
Guess I'll have to use ESR then :/
