### ISSUE TITLE
Compatibility with Multiple Tab Handler add-on

### ISSUE THREAD

**Issue by danwep** [Croydon/vertical-tabs-reloaded#49]
Add-on version: 0.6.1
Firefox version: 46.0.1
OS + OS-Version: Linux, Debian testing[codename stretch]

Multiple Tab Handler[MTH][0] add-on does not work when Vertical Tabs
Reloaded[VTR] is enabled. The only installed add-ons where VTR and
MTH, in a new profile to avoid any conflicts with other add-ons and/or
user settings.

Thank You

[0] https://addons.mozilla.org/en-US/firefox/addon/multiple-tab-handler/

**Comment by Croydon** [comment]
@danwep Please get more specific what exactly is not working.

**Comment by gamingexpert13** [comment]
I'm not the original poster, but I have the same issue. Multiple Tab Handler is an addon to give you the ability to select multiple tabs at a time to perform actions like moving them as a group, closing them, saving the contents from them, opening them in a new window, etc. 

There are two ways for selecting multiple tabs: hold ctrl and click multiple tabs, or click on the first tab, then hold shift, and click on the last tab and all tabs in between will be selected. Neither of those actions work with VTR enabled.

**Comment by danwep** [comment]
Never got an email about your question @Croydon. Just like @gamingexpert13 explained. Basically MTH does not work at all.

**Comment by Luckz** [comment]
https://github.com/darrinhenein/VerticalTabs/blob/master/multiselect.jsm was the old multiple tab selection code, before some misguided folks ripped it out while annihilating 'groups' support.

**Comment by unknown--** [comment]
Please add multiple tab selection back. I use it quite a bit and I can't say I've ever had any problems when using it.

**Comment by LostPolygon** [comment]
Please bring it back, I can't imagine Firefox without ability to multi-select tabs anymore. I'll have to revert to some ancient version with multi-select support, unfortunately.

**Comment by Croydon** [comment]
To the people who need this feature: Your best shot right now is to express your support for multiselect here: https://bugzilla.mozilla.org/show_bug.cgi?id=566510

Tell Mozilla why you need it.
____

I won't add the old code again. It's buggy and would break anyway again for good with the transition to WebExtensions. I have experimented with outsourcing this to an own add-on, but for the very same reason it's not reasonable to do this.

I also won't try to make VTR compatible with the current version of Multiple Tab Handler. It's a XUL add-on and will break at the end of 2017. When the add-on gets rewritten as a WebExtension I might look into it again, but for now, no.

So please, go ahead and tell Mozilla that multiselect would be a good addition to Firefox.

**Comment by Croydon** [comment]
🎉🎉 Thanks to a Google Summe of Code Student Firefox will finally get multi-tab handling support!

**Comment by Croydon** [comment]
This will make the Multiple Tab Handler add-on obsolete.

Closing this in favor of #190
