### ISSUE TITLE
Keep close tab button persistant across all themes (not just show on hover)

### ISSUE THREAD

**Issue by jonasflint** [Croydon/vertical-tabs-reloaded#52]
I like to just use the favicon as tabs and keep the tab bar super narrow: 
screenshot: http://d.pr/i/139TF

This works well, because to close a tab I can just simply middle click on that tab.  But on my 13 inch macbook where am using the trackpad it's not so easy.  I have to show the close button, which is fine, 
only the close button only shows up on the selected tab or when you hover over a tab.  When you hover it shifts everything over to reveal the close button.  This shift is annoying. It would be better to just have the close button persistant like it is on the selected tab.

screenshot: http://d.pr/i/jFQr

This may be resolved with custom themes. 

Add-on version:
Firefox version:
OS + OS-Version:

**Comment by jonasflint** [comment]
Add-On Version: 0.6.2
Firefox Version: 46.0.1
Mac OSX El Capitan 10.11.5

**Comment by Croydon** [comment]
I can't reproduce this shift on Windows. 
I'm also not sure yet what this has to do with themes. Does the shift only happen in some themes? If yes, in which ones?

**Comment by jonasflint** [comment]
This is happening on the dark and light themes (which are the best ones in my opinion)  Here is a couple are a couple of quick  screenshots / screencasts to show you whats happening:

tab mix plus settings: http://d.pr/i/17gYL
Dark Theme: http://d.pr/v/euxz
Light theme: http://d.pr/v/15BGm

it does NOT happen when using no theme. (but the no theme has weird spacing issues, so I don't use it).

**Comment by Croydon** [comment]
@jonasflint The compact mode (see #55) might improve the situation for you.

I'm planing that custom themes (see #40) will be able to change the behaviour of the close button. I'm not planning any further changes regarding this issue so far since this scenario can only happen with thirdparty add-ons (Tab Mix Plus), but I'm staying open minded and listen to feedback. 😄

**Comment by jonasflint** [comment]
Sounds good. Yeah, I think custom themes will be the holy grail for this. And if you do that. I might contribute a few custom themes.

BTW,  compact mode is a excellent addition! Thanks!

**Comment by Croydon** [comment]
Since there won't be any compatibility of this kind possible in a WebExtensions-only world this bug did become somewhat invalid.
More info at #13.

**Comment by Croydon** [comment]
By the way, custom themes will totally happen at some point 😄
