### ISSUE TITLE
Feature request: when closing a tab, always give focus to tab above it.

### ISSUE THREAD

**Issue by mbaz** [Croydon/vertical-tabs-reloaded#54]
Add-on version: 0.6.2.
Firefox version: 47.0
OS + OS-Version: Arch Linux

I'd find it useful if there was an option to always focus on the tab "above" when closing a tab. By default (at least on my setup), sometimes the bottom tab is selected.

**Comment by Croydon** [comment]
Currently I tend to say this is out of the scope of the add-on.
Even in a WebExtentions world 3rd party add-ons should be able to decide which tab gets selected after another one gets closed.

**Comment by mbaz** [comment]
I hope this kind of functionality can be exposed, either by the add-on or firefox itself. Current behavior is inconsistent and, I think, not configurable.

**Comment by Croydon** [comment]
Closed in favor of #96.
