### ISSUE TITLE
Add option to hide toolbar

### ISSUE THREAD

**Issue by krigstask** [Croydon/vertical-tabs-reloaded#57]
I use VTR together with Vimperator, and I don't really that toolbar with "New tab" button.  It takes space and for some reason it's ugly bright grey on my box, despite dark themes everywhere.  It'd be nice to be able to hide it.

**Comment by Croydon** [comment]
Could you please make a screenshot where I can see clearly how the toolbar looks with your setting?

The option will be implemented with the next update (might take some time).

**Comment by krigstask** [comment]
> Could you please make a screenshot where I can see clearly how the toolbar looks with your setting?

Sure:
![tmp](https://cloud.githubusercontent.com/assets/419654/17392066/d24bf394-5a2b-11e6-8367-38de5d1b79e6.png)

> The option will be implemented with the next update (might take some time)

Sure, no hurry.  I move it to the bottom for the time being, and that's almost fine.  Thank you!

**Comment by Croydon** [comment]
I have tested to add an option to hide the toolbar and for some reason it doesn't work with pinned tabs. ba884bec1480c755447fb328d53274b2411ac778

Pinned tabs gets unpinned after every restart of Firefox. I have no clue why If someone knows more about that, let me know :)

**Comment by krigstask** [comment]
Sorry it took me so long, I was on-and-off the keyboard in January.
Also I couldn't promptly test your branch, probably because 0.8.x isn't compatible with Fx ESR =\
I'll look for a way of trying it some more, thanks for draft implementation!

**Comment by Croydon** [comment]
Starting with FFv57 (see #13) VTR will have a custom toolbar. "Thanks" to that it will be possible to hide the toolbar without negative consequences.

**Comment by woj-tek** [comment]
OK, I was just playing with VTR options and noticed it's possible to set toolbar to top/bottom and I was meaning to suggest another option "off" but... I'm glad it's on to-do list already :-)

**Comment by Croydon** [comment]
Fixed in the experimental new WebExtension sidebar. Will still take some time till it lands as a stable feature in a stable version. More information at #13.

**Comment by krigstask** [comment]
@Croydon, I've got a bit confused by a multitude of branches and versions.  Could you please clarify what branch or version could I try on **Fx 52 *ESR*** to test this fix?  Thanks again for your work, by the way!

**Comment by Croydon** [comment]
@krigstask Unfortunately, you can't. There is no support for FF52 ESR anymore in newer versions. Read why here: https://github.com/Croydon/vertical-tabs-reloaded/issues/13#issuecomment-271294600

Also the fix is included in the new WebExtension tab sidebar which is right now incomplete. This sidebar will be testable in a version with FF55, becoming default in FF56 and will be the only useable sidebar in FF57.

**Comment by Croydon** [comment]
So you will get this feature eventually, but if you stay on the ESR channel it will still take a long time. To be more specific till the next ESR version is released.

**Comment by krigstask** [comment]
@Croydon, all right, I can wait just fine =)
Thanks again!
