### ISSUE TITLE
Ideas, additions

### ISSUE THREAD

**Issue by m0n** [Croydon/vertical-tabs-reloaded#59]
- [ ] make an option for pinned tabs be in a fixed area (like on Firefox's default tab-bar)
- [ ] a button to hide/show pinned tabs labels. If no labels then pinned icons must flow like normal text
- [ ] since CTRL+number switches tabs, an option would be nice to display the first 9 tabs index (useful to switch between most frequently used pinned tabs)
- [ ] add HOME, END buttons (possibly to the right side of the toolbar)
- [ ] optionally handle HOME,END,UP,DOWN (maybe PGDN,PGUP) keys

**Comment by Croydon** [comment]
1) See issue #2.
2) See issue #20.
3) Sorry, but this seems to be a too specific whish. I can't see a broader audience for that, but if more people want this I will think about it again.
4) See your own issue #60. I don't plan to add more buttons in the toolbar via default, but if it's customizable everyone can do what they want.
5) Please explain this further. What should happen for each key? What has it to do with vertical tabs? Can't you use some default Firefox hotkey?

**Comment by Croydon** [comment]
@m0n Please provide further feedback or I will close the issue.

**Comment by Croydon** [comment]
Closed because of missing feedback. @m0n Feel free to still provide more information.
