### ISSUE TITLE
hide/show vertical tabs

### ISSUE THREAD

**Issue by panosl** [Croydon/vertical-tabs-reloaded#6]
have an option like cmd+opt+t to hide/show the vertical tabs.

My experience is that since I switched to ultrawide monitor I have 2 windows of firefox open at times and I only keep the tab bar open on the base one and just need a base window with no tab bar on the one I'm doing a quick search on, thus being it's not need (the vertical tab bar).

**Comment by Croydon** [comment]
@panosl Will be getting shipped in v0.4.0.
The default hotkey will be control-alt-v, however it is easily changeable in the settings.

**Comment by panosl** [comment]
Awesome news :)
