### ISSUE TITLE
Attempting to switch to the first pinned tab sometimes closes it spontaneously

### ISSUE THREAD

**Issue by DavidJCobb** [Croydon/vertical-tabs-reloaded#61]
When the first pinned tab in a window is open to Facebook, and when I try to switch from another tab back to that one, it will spontaneously close. This is not the bug where tabs are hidden; using CTRL+TAB and CTRL+SHIFT+TAB to cycle through tabs confirms that the Facebook tab is completely lost. I mention Facebook because that actually seems to be the only tab that this happens to, oddly enough.

---

Add-on version: 0.7.0
Firefox version: 47.0.1
OS + OS-Version: Windows 10 Pro
Other tab + user interface related add-ons: Download Status Bar; The Addon Bar (restored)

**Comment by DavidJCobb** [comment]
UPDATE: Undo Close Tab can recover the lost tab. Still irritating, though.

**Comment by DavidJCobb** [comment]
Seems to happen more often if I try to switch back to the first tab after having just closed another tab.

**Comment by kristjaneerik** [comment]
This is happening to me for a variety of google.com subdomains for several pinned tabs, not just the first one. It also happens with multiple mice and a touchpad.

Add-on version: 0.7.0
Firefox version: 48.0.1
OS: OS X El Capitan Version 10.11.6
Other add-ons: Tab Groups

**Comment by DavidJCobb** [comment]
The tab closure works exactly the same as a normal one.

If you try to close a Facebook tab while typing a status update, Firefox catches it and asks you if you're sure (because JavaScript on Facebook's site catches a close attempt). If you leave text in there, switch away from the tab, and come back,... this bug will trigger that same confirmation prompt. So the tab isn't just disappearing -- something is specifically telling Firefox to close it.

**Comment by DavidJCobb** [comment]
Well, I tried moving the affected tab to the second in the list, and the problem still happened... to it. So the problem isn't with the first tab in the list. If I have a pinned tab open to the URL <https://www.facebook.com/?sk=nf>, then there is a random chance that Firefox will close it when I click on it while this add-on is installed.

Haven't tested whether it happens in any browser window or just the first one open, though.

**Comment by DavidJCobb** [comment]
Just had it happen to the first tab in my third browser window. I guess it isn't specific to Facebook, but is specific to pinned tabs (or tabs restored from a prior session?).

**Comment by mbaz** [comment]
Add-on version: 0.8.2
Firefox version: 52.0.1 (64 bit)
OS: Arch Linux
Other add-ons: Zotero, VimFx, uMatrix

I started using pinned tabs recently and I'm also seeing similar behavior. I can't point out exactly how to reproduce this, as it happens only rarely, but it's happened over diferent pinned tabs on different windows; I don't think this is specific to certain websites. Undo Close Tab indeed brings the tab back.

**Comment by Croydon** [comment]
Indeed just very randomly reproducable without clear pattern.
As far as I know it has nothing to do with the website itself.

Sounds like another crazy XUL thingy, which will go away with the porting to WebExtensions (see #13).
May still take some time but is the only stable solution.

**Comment by Croydon** [comment]
Fixed by #13 in general. Pinned tabs implemented with bc3b43ec6ce6a6ac10dcb4e5362f9d95fcc7a7cf

Will still take some time till it lands as a stable feature in stable version of VTR. Please be patient 😄
