### ISSUE TITLE
Cannot find "New Tab" button in the Toolbar

### ISSUE THREAD

**Issue by Cepr0** [Croydon/vertical-tabs-reloaded#62]
Hello! 
I could not find the button "New Tab" in the Toolbar. How can I add it to the Toolbar?
Could you add it by default?

![01 09](https://cloud.githubusercontent.com/assets/10778600/18156663/9433dd50-7020-11e6-95a1-55d578e3c623.png)

Add-on version: 0.7.0
Firefox version: 48.0.2
OS + OS-Version: Win7 x32
Other tab + user interface related add-ons: https://addons.mozilla.org/en-US/firefox/addon/tab-mix-plus/

**Comment by Croydon** [comment]
With some update in the future it will be possible to customize the toolbar with the Firefox customization menu. 

Right now, the toolbar contains all elements, which the toolbar contains anyway (read: the elements you have there without VTR installed). So if you miss there something, you cann disable VTR, customize it, and re-enable VTR. 

The new tab button should be there via default already.

**Comment by Croydon** [comment]
@Cepr0 Have you tried to expand the size of the tabbrowser/toolbar? Maybe it is getting hidden.

**Comment by Cepr0** [comment]
Hi! I've found 'new tab' button ))
It was controlled by TabMix Plus.
I switched 'new tab' button to position 'on the right' and re-enabled your addon.
And the button appeared:

![2016-09-01_20-24-32](https://cloud.githubusercontent.com/assets/10778600/18177271/277340f4-7082-11e6-9fc0-72b22a1bf3f3.png)

**Comment by Croydon** [comment]
@Cepr0 I'm glad that you figured it out :)

Closed in favor of #60.
