### ISSUE TITLE
Place tab title and the toolbar buttons on the Firefox titlebar

### ISSUE THREAD

**Issue by Cepr0** [Croydon/vertical-tabs-reloaded#63]
After 'vertical-tabs-reloaded' installed it move all buttons from Firefox titlebar to the own toolbar.
So we have a lot of unused space above Firefox window. I think it will be pretty nice if you place a title of the current Tab and the toolbar buttons on the Firefox titlebar:

![01 09-](https://cloud.githubusercontent.com/assets/10778600/18157931/c97c19fc-7028-11e6-841c-b1db9feb43c9.png)

Add-on version: 0.7.0
Firefox version: 48.0.2
OS + OS-Version: Win7 x32
Other tab + user interface related add-ons: https://addons.mozilla.org/en-US/firefox/addon/tab-mix-plus/

**Comment by Croydon** [comment]
The title is there already via default.
Placing buttons in the titlebar is absolutely impossible for me in a WebExtensions-only world.

If you want this please request such a feature from Firefox.
