### ISSUE TITLE
Feature request: compact tabs

### ISSUE THREAD

**Issue by riot26** [Croydon/vertical-tabs-reloaded#66]
I made this with userstyles and it works not so good. Want to see same feature in your addon

default view:
![default](http://i.imgur.com/xLnhAYH.png)

on hover:
![on hover](http://i.imgur.com/zo258Wq.png)

[userstyle on gist](https://gist.github.com/riot26/e8809a9b4a2b84e586f889269f98e2d5)

i have latest addon (0.7.0) in latest firefox (48.0.2) in latest majaro linux (arch-based, xfce) (16.08)

**Comment by myBestSoftAndPref** [comment]
**Compact tabs for Vertical Tabs Reloaded**
https://userstyles.org/styles/133396/compact-tabs-for-vertical-tabs-reloaded
<img src="https://userstyles.org/style_screenshot_thumbnails/133396_after.png?r=1475486042" />

**Comment by Croydon** [comment]
There is no way that WebExtension add-ons can resize their own sidebar automatically. (https://bugzilla.mozilla.org/show_bug.cgi?id=1346490, https://bugzilla.mozilla.org/show_bug.cgi?id=1357567)

Therefore I see no way to implement this. Sorry.
