### ISSUE TITLE
Show tab status

### ISSUE THREAD

**Issue by myBestSoftAndPref** [Croydon/vertical-tabs-reloaded#67]
Hello,
I am offering build user CSS style for tab status color (works with your light theme) into your addon:
https://userstyles.org/styles/119083/tree-style-tab-tabs-color-active-un-read-selected

Of course it can be optional available though addon configuration.

**Comment by myBestSoftAndPref** [comment]
Color blind variant compatible with default Firefox and vertical-tabs-reloaded (light and dark) theme.
**Tab's status color blind variant** 
https://userstyles.org/styles/133232/tab-s-status-color-blind-variant

**Comment by Croydon** [comment]
@myBestSoftAndPref Thank you! I consider accessibility a really important aspect. I will look into it when I have time :)

In general, at some point there will be custom themes #40 so I won't add too many styles via default, but an option for color blind people sounds awesome :)

**Comment by Croydon** [comment]
Thanks @myBestSoftAndPref, I have added the colorless variant as an opt-in option.

Will be included in a release in something like 3 months from now.

**Comment by Croydon** [comment]
By the way, I did choose the colorless variant to make it compatible with every single theme out there.
