### ISSUE TITLE
Feature request: display url on tab hover

### ISSUE THREAD

**Issue by dafunk91** [Croydon/vertical-tabs-reloaded#68]
Please add this feature for tab whores and low ping bastards :P
Just an irony, nothing personal bout tab whoring :)

http://www.imagebam.com/image/15c551511565408

**Comment by myBestSoftAndPref** [comment]
I think we don't need in combine. We already have https://addons.mozilla.org/ru/firefox/addon/tabtooltip/

**Comment by Croydon** [comment]
tabTooltip seems to work fine with VTR, please use this add-on (or something similar) if you want this feature. I consider it as out of scope for VTR.
