### ISSUE TITLE
Plugin doesn't change anything

### ISSUE THREAD

**Issue by bdelv** [Croydon/vertical-tabs-reloaded#69]
Add-on version: 0.7.1
Firefox version: 50.0.2
OS + OS-Version: Xubuntu 16.10
Other tab + user interface related add-ons: None

After installing the plugin, no vertical tabs appear.
When pressing the hotkey (ctrl+alt+v), the console writes:

console.error: vertical-tabs-reloaded: 
  Message: TypeError: objectScope[("vt" + windowID)] is undefined
  Stack:
    initHotkeys/GLOBAL_SCOPE.vtToggleDisplayHotkey<.onPress@resource://gre/modules/commonjs/toolkit/loader.js -> resource://verticaltabsreloaded-at-go-dev-dot-de/index.js:73:4
onKeypress@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/keyboard/hotkeys.js:102:7
emitOnObject@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:112:9
emit@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/event/core.js:89:38
handleEvent@resource://gre/modules/commonjs/toolkit/loader.js -> resource://gre/modules/commonjs/sdk/keyboard/observer.js:53:5

**Comment by bdelv** [comment]
Update:
Same behavior on other computers
- another Xubuntu 16.10 / Firefox 50.0.2
- Windows 10 / Firefox 50.0.2

First instance of Firefox doesn't show the plugin. Second instance shows it.

**Comment by bdelv** [comment]
Duplicate.
Works if I switch from "Never remember history" to "remember history"

**Comment by Croydon** [comment]
Duplicate of #41.
