### ISSUE TITLE
Feature request: reverse order tablist, ie a tab stack

### ISSUE THREAD

**Issue by jackpipe** [Croydon/vertical-tabs-reloaded#70]
Add-on version: latest
Firefox version: 45
OS + OS-Version: OS X 10.11.6
Other tab + user interface related add-ons: None

I'd like to see an option to reverse the order of the list, so that new tabs are added at the top of the list, which push down the other tabs.  ie it becomes a tab stack.  I added this myself in the original VerticalTabs, by adding:

`tabs.mTabstrip.dir = "reverse";`

and I think I had to make it draw from the top, possibly with:

```tabs.align = "start";```
and
```leftbox.insertBefore(toolbar, leftbox.firstChild);```

all in the function `rearrangeXUL: function() {}`, but I didn't submit changes.

I will try it myself and submit a pull if I can get it to work, though I think the new firefox security thing stops you loading your own addons unless they're signed.

**Comment by Croydon** [comment]
I would accept a clean and small implementation of this feature, when the feature is opt-in.

@jackpipe You can load unsigned add-ons temporary in about:debugging or use other Firefox Editons like the Developer Edition or Nightly.

**Comment by Croydon** [comment]
Closed in favor of #96.
