### ISSUE TITLE
If no hotkey provided

### ISSUE THREAD

**Issue by roman4e** [Croydon/vertical-tabs-reloaded#72]
If nothing in field 'hotkey' console log produces an error
Can be fixed with adding in _index.js_
line 69:
`      if ( /^\s*$/.test(toggleKey) !== true ) {`
line 77:
`      }`

Add-on version: latest
Firefox version: 50
OS + OS-Version: Linux Mint 18
Other tab + user interface related add-ons:

**Comment by Croydon** [comment]
Actually, it's not THAT easy.
It doesn't cover all cases, e.g. what if the last saved key was an empty string? Then it tries to destroy an non-existing hotkey object.

Do you want to work out a solution and create a pull request? :)

**Comment by Croydon** [comment]
Fixed. Will be included in a release circa 3 months from now.
