### ISSUE TITLE
Any way I can load the extension in `about:debugging`? (or by `web-ext run`)

### ISSUE THREAD

**Issue by PikachuEXE** [Croydon/vertical-tabs-reloaded#77]
Add-on version: `0.8.0` + branch `master` or `webext-fx53`
Firefox version: FF Dev 53
OS + OS-Version: Windows 7

I am using FF Dev 53 on Windows 7.
VTR 0.8.0 from official addon website works fine.
But running `master` or `webext-fx53` locally doesn't work.

**Comment by Croydon** [comment]
You need the jpm tool, then execute jpm xpi.
Afterwards you can install it via about:debugging, drag and drop or the other common ways.

**Comment by PikachuEXE** [comment]
I just wonder how the theme works when Fx 57 released
Coz it seems that the style loading depends on `sdk/stylesheet/utils` which is from addon SDK not web extension
https://github.com/Croydon/vertical-tabs-reloaded/blob/webext-fx53/lib/verticaltabs.js#L12

**Comment by Croydon** [comment]
@PikachuEXE As you can see in issue #13 the rewriting as a WebExtensions is a work in progress and nowhere close to be finished.
Currently it's a SDK add-on with an embedded WebExt. Everytime I can rewrite a part of VTR I move a small-ish part to WebExt.

**Comment by Croydon** [comment]
By doing so the add-on is working at every point of the rewriting.
