### ISSUE TITLE
Restored but unloaded tabs are titled "New Tab"

### ISSUE THREAD

**Issue by Stebalien** [Croydon/vertical-tabs-reloaded#80]
Add-on version: 0.8.0
Firefox version: 51.0.1
OS + OS-Version: Arch Linux

When `browser.sessionstore.restore_on_demand` is set, all restored tabs *except* the tab focused on start are titled "New Tab". They retain this title even after they're loaded/navigated.

**Comment by Croydon** [comment]
There is sometimes an issue with the very first tab, but never noticed or heard of problems with all tabs except the focused one.

Are these regular tabs? Pinned?
Do you have any add-ons interfering with tabs or the session mangement/storage?

**Comment by Stebalien** [comment]
So, apparently hiding the toolbar (`TabsToolbar {display: none;}`) caused this. Any idea why? Changing it to visibility collapse fixes it.

**Comment by Croydon** [comment]
XUL is unloading events when the respective UI elements are getting hidden, which has crazy outcomes sometimes. I assume this could cause it.

For hiding the toolbar see #57.
