### ISSUE TITLE
Extension no longer works with Firefox Nightly

### ISSUE THREAD

**Issue by asampal** [Croydon/vertical-tabs-reloaded#83]
As of a couple of days ago, VTR no longer works with Firefox Nightly. At the time the break first occurred, Firefox had made a change that affected sessions and it also broke Tab Mix Plus, which I use in combination with VTR. Tab Mix Plus has since had another build out which makes it work with the Nightly.

Add-on version: 0.8.2
Firefox version: 55.0a1 (2017-04-22) (64-bit)
OS + OS-Version: Windows 10 Creators Update
Other tab + user interface related add-ons: Tab Mix Plus Dev-Build 0.5.0.3pre.170421a1

**Comment by Croydon** [comment]
Caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1352069

Rename browser.tabs.animate -> toolkit.cosmeticAnimations.enabled

**Comment by asampal** [comment]
@Croydon,  could you set up a development version of the extension if you're not ready to make a full release for it with just this fix?

**Comment by Croydon** [comment]
I already pushed v0.8.3 to AMO, it's in the review queue.
