### ISSUE TITLE
Tab content is shifting when the tab is busy

### ISSUE THREAD

**Issue by Keith94** [Croydon/vertical-tabs-reloaded#85]
Add-on version: 0.8.3
Firefox version: 54.0a2
OS + OS-Version: Windows 8
Other tab + user interface related add-ons: N/A

The tab spinner, title, and close icon seems to shift a few pixels when the tab is busy (while reloading it)

![2017-04-23_23-07-38](https://cloud.githubusercontent.com/assets/5490615/25324294/eaccb5a8-2879-11e7-9e4d-6f14fe95bbd1.gif)

**Comment by Croydon** [comment]
Fixed in the upcoming WebExtension version.
