### ISSUE TITLE
Default settings fallback isn't working

### ISSUE THREAD

**Issue by Keith94** [Croydon/vertical-tabs-reloaded#86]
Add-on version: 0.8.3
Firefox version: 54.0a2
OS + OS-Version: Windows 8
Other tab + user interface related add-ons: None

With HTML5 fullscreen videos (youtube, twitch etc.) the tab bar should not be visible.

![image](https://cloud.githubusercontent.com/assets/5490615/25360598/ac451890-28fe-11e7-97eb-b2ad3433d286.png)

**Comment by Croydon** [comment]
It shouldn't.

Please provide all information to give me a chance to reproduce.

**Comment by Keith94** [comment]
I edited the OP.

**Comment by Croydon** [comment]
I noticed that it gets unhidden on an add-on update while in fullscreen. Just to make sure, it wasn't an one time thing?

**Comment by Keith94** [comment]
No, the bug is always reproducible.

**Comment by Croydon** [comment]
I'm still not able to reproduce this.

Are you also sure that you have set the respective VTR setting in the add-on manager?

**Comment by Keith94** [comment]
Yes, but that setting does not affect this bug either way.

**Comment by Croydon** [comment]
I could reproduce this in a new profile.

In v0.8.3 there is a initializing bug for settings, which doesn't seem to exist anymore in current master.

After unchecking and checking the "hide tabs in fullscreen" checkbox the setting is saved as whished. Then it works for me.

**Comment by Croydon** [comment]
v0.8.3.1 is on its way.

Thanks for reporting @Keith94!
The code actually had serveral issues leading to this situation.

The lesson I learned is to test more often with clean profiles 🙄
