### ISSUE TITLE
Add toolbar button to toggle tabbar

### ISSUE THREAD

**Issue by woj-tek** [Croydon/vertical-tabs-reloaded#88]
Add-on version: 0.8.3 / 24.04.2017
Firefox version: 53.0
OS + OS-Version: macOS Sierra 10.12.4
Other tab + user interface related add-ons: n/a

Currently we have a shortcut to toggle (show/hide) the tabbar - it would be great to have a toolbar button that would do just that - toggle visibility of tabbar

**Comment by Croydon** [comment]
Already done in the dev version a while ago 😄 

8f72143ef736f6a579d02ccd595d166743b456f1
