### ISSUE TITLE
Close/Minimize/Hamburger Buttons overlap

### ISSUE THREAD

**Issue by zilluss** [Croydon/vertical-tabs-reloaded#9]
When Vertical Tabs is enabled, the window buttons overlap the back button see the attached image.
<img width="121" alt="screen shot 2015-08-24 at 17 13 34" src="https://cloud.githubusercontent.com/assets/673648/9443840/b0f1c678-4a83-11e5-867a-c9ea1c384454.png">

**Comment by Croydon** [comment]
@zilluss Sorry, for not answering "in a while". 

If you should still be interested in this addon could you please try it again and check if the config `browser.tabs.drawInTitlebar` is set to `false`? You can change/see this setting if you are entering `about:config` in your Firefox and search for the string. 

Does it solve the problem?

**Comment by Croydon** [comment]
Does anybody else have such a problem? If yes, can it be solved for you with `browser.tabs.drawInTitlebar` set to `false`?

**Comment by xxdavid** [comment]
I haven't had this issue since yesterday. That setting fixes it. Thank you for your support. :smiley:

**Comment by Keith94** [comment]
Maybe the add-on should automatically set that `browser.tabs.drawInTitlebar` preference to false when it's first installed? Since having the window controls overlapping is not very desirable.

**Comment by Croydon** [comment]
@Keith94 That is exactly my plan for the next version. The original add-on was setting this preference to false on every single startup which was quite annoying and undesirable, since it is not always required.

I might also add in further version an option in the settings to easily toggle this preference.

**Comment by Croydon** [comment]
The v0.5.0 update will set `browser.tabs.drawInTitlebar` one time to false. In the future it will happen if you install the add-on.

I might also add in a further version an option in the settings to easily toggle this preference.

**Comment by woj-tek** [comment]
I would say that setting it by default would be better (was just struggling with it for a bit). Or make it explained very well in the settings.

**Comment by Croydon** [comment]
@woj-tek It is getting set by default on new installations and when updating to v0.5.0. So it is the default :)

**Comment by Croydon** [comment]
I have decided to leave this issue open since I am still not happy with this workaround.

**Comment by woj-tek** [comment]
Hmm, then something did not work as I installed the 0.5.0 fresh and the setting wasn't set, hence my above comment :-)

**Comment by woj-tek** [comment]
OK, so I've just installed the extension on another machine (this time osx) and had the same problem - had to manually change the `browser.tabs.drawInTitlebar`...

**Comment by Croydon** [comment]
@woj-tek What other add-ons do you have installed in these setups?

**Comment by woj-tek** [comment]
Here's the list... I think I need to clean up this list a bit...

Name | Version | Enabled
---- | ------- | -------
asciidoctorjslivepreview | 0.5.1 | true
Customizable Shortcuts | 0.9.8 | true
Do This Automatically | 0.81.1-signed | true
Download Panel Tweaks | 1.3.2 | true
Download YouTube Videos as MP4 | 1.8.7 | true
FindBar Tweak | 2.1.9 | true
FireGestures | 1.10.7 | true
FlashGot | 1.5.6.13 | true
Google™ Translator | 0.4.5 | true
Greasemonkey | 3.7 | true
Hide Plugin Bar | 0.1.1 | true
Hide Unwanted Results of Google Search | 1.6 | true
New Tab Override (browser.newtab.url replacement) | 2.3.1 | true
Nimbus Screen Capture - editable screenshots. | 8.2.1 | true
NoSquint | 2.1.9.1-signed | true
oldbar | 1.2.1-signed | true
OpenDownload² | 4.1.1 | true
Private Tab | 0.1.9.1 | true
RSS Icon in url bar | 1.5.2 | true
Saved Password Editor | 2.9.6 | true
Secure Login | 1.1.9 | true
Selected Search | 0.4.160328 | true
Session Manager | 0.8.1.12 | true
Single Key Tab Switch | 0.2.7 | true
Tab Counter | 1.9.9.3 | true
uBlock Origin | 1.6.8 | true
UnMHT | 8.1.0 | true
Vertical Tabs Reloaded | 0.5.0 | true
YouTube Center Developer Build | 538 | true
YouTube Video and Audio Downloader | 0.5.0 | true
Adblock Edge | 2.1.9.1-signed.1-let-fixed | false
Click-to-Play Manager | 1.4 | false
Firefox Hello Beta | 1.2.1 | false
Free Download Manager extension | 2.0.19 | false
Ghostery | 6.1.0 | false
Location Bar Enhancer | 5.3 | false
Mouse Gestures Suite | 2.3.1 | false
Stylish | 2.0.6 | false
Tabs on Bottom | 0.7.1 | false
Tree Style Tab | 0.17.2016031101 | false
Turbo Download Manager | 0.2.4 | false
YouTube High Definition | 45.1 | false

**Comment by Croydon** [comment]
@woj-tek I just retried this with a new profile. No problem there. So my assumption is that one of your other add-ons is resetting the preference. Please forgive me that I don't have the time to test it with all of the add-ons you just mentioned. Maybe you should really try to reduce them :)

**Comment by woj-tek** [comment]
It's not they are "resetting" the setting (because after the change property sticks) but rather prevent VTR to change it...

anyhow, I'lve cleaned the list a bit, but I think I need to reset Fx profile either way after all this time :-)

**Comment by Croydon** [comment]
**If somebody is still experience this problem, then please either set `browser.tabs.drawInTitlebar` manually to `true` in `about:config` or starting with v0.6.0 use the toggle button in the Vertial Tabs Reloaded preferences in the Firefox add-on mananger. Thank you.**

**Comment by woj-tek** [comment]
OK, not exactly problem with overlaping controlls, but when using Dark Developer theme (vide https://addons.mozilla.org/en-US/firefox/addon/devedition-theme-enabler/) and enabling the titlebar it remains white (system colour).
With vertical tabs disabled and drawInTitlebar=false it is simply drew as dark (themed)
