### ISSUE TITLE
Doesn't work in Nightly

### ISSUE THREAD

**Issue by Keith94** [Croydon/vertical-tabs-reloaded#99]
Add-on version: 0.8.3.1
Firefox version: 55.0a1
OS + OS-Version: Windows 8
Other tab + user interface related add-ons: N/A

Installing the add-on in a clean profile doesn't seem to work. Horizontal tabs are still visible and the vertical tabs don't appear. Browser Console:

>1496804879569	addons.xpi	WARN	Failed to remove temporary file C:\Users\x\AppData\Local\Temp\tmp-168.xpi for addon https://addons.mozilla.org/firefox/downloads/latest/vertical-tabs-reloaded/platform:5/addon-616590-latest.xpi?src=dp-btn-primary: [Exception... "Component returned failure code: 0x80520015 (NS_ERROR_FILE_ACCESS_DENIED) [nsIFile.remove]"  nsresult: "0x80520015 (NS_ERROR_FILE_ACCESS_DENIED)"  location: "JS frame :: resource://gre/modules/addons/XPIInstall.jsm :: removeTemporaryFile :: line 1595"  data: no] Stack trace: removeTemporaryFile()@resource://gre/modules/addons/XPIInstall.jsm:1595 < startInstall/<()@resource://gre/modules/addons/XPIInstall.jsm:1963

>Use of nsIFile in content process is deprecated. loader.js:247:15

>Error: The object could not be cloned.  undefined

**Comment by KuoE0** [comment]
It also doesn't work on macOS 10.12.4.

**Comment by Croydon** [comment]
Windows seems still to work. "Only" Linux and macOS broke.

**Comment by Croydon** [comment]
Correction: v0.8.3.1 is indeed broken on all platforms. The current dev version is working, however.

**Comment by Croydon** [comment]
I'm likely not going to solve this for now. Nightly is not a high priority and my time is very fragmented over several projects. The current dev/master version works as expected and will become the stable release before FF55 goes stable.

**Comment by ojab** [comment]
I (and a bunch of other people) have used TabCenter for vertical tabs, but it [will not be supported at all in Fx >55](https://github.com/bwinton/TabCenter/pull/1103#issuecomment-308122056) (latest nightly is already 56). 
vertical-tabs-reloaded looks like the most suitable replacement, so the question is which version should support Fx 55+?
AFAIU it is 0.8.4 and this issue depends on https://github.com/Croydon/vertical-tabs-reloaded/issues/13?
I'm not asking about time frame, just want to know which version should I try on Fx 55+ with expectation to have more-or-less working vertical tabs.

**Comment by Croydon** [comment]
@ojab I understand this. v0.8.4 will support FF55+, this version will get released shortly FF55 gets released.

If it is helpful I can provide the current developer version (which is the version in the master branch) as a .xpi file here in a few hours. Alternatively, you can create the xpi file by yourself by using the jpm tool.

**Comment by ojab** [comment]
It will be really awesome if you could push it to the beta channel on AMO, so it will be signed & anyone be able to install it without changing Fx security settings.

**Comment by Keith94** [comment]
@ojab There's actually a WebExtensions replacement for TC here: https://github.com/eoger/tabcenter-redux

**Comment by Croydon** [comment]
> It will be really awesome if you could push it to the beta channel on AMO

I will likely create a beta channel at some point, but not in the foreseeable future, since I need to manually maintain it permanently then.

For now, here is the alpha version which works in Nightly:

[vertical-tabs-reloaded-0.8.4-alpha.zip](https://github.com/Croydon/vertical-tabs-reloaded/files/1072842/vertical-tabs-reloaded-0.8.4-alpha.zip)


@Keith94 It's completely okay for me if you use another vertical tab solution or several at the same time or switch back and forth. Even more when the other solutions are open source as well. However, it isn't really nice if you report bugs for project A and then advertise project B in these bug reports. And that is generally true, no matter if it is about my project or another.

**Comment by Croydon** [comment]
If somebody was quick and already tried the .zip file before: please retry :)

**Comment by Croydon** [comment]
I actually reconsidered. There you go https://addons.mozilla.org/de/firefox/addon/vertical-tabs-reloaded/versions/beta // @ojab

**Comment by edduarte** [comment]
Seems to work great on the Nightly version. The only issue I came across so far is that tabs remain visible in fullscreen, or when viewing YouTube videos in fullscreen, regardless of the option "Hide tabs in fullscreen" being enabled or disabled. (Windows 10 x64, Firefox 55.0b2 64-bit)

Thanks for all the hard work! 👍

**Comment by leedoyle** [comment]
@Keith94 as far as I know, Tabcenter Redux still requires you to hide the default tab bar with another addon. Has it changed?

**Comment by Keith94** [comment]
@leedoyle Can't be done yet on Firefox's side: https://bugzilla.mozilla.org/show_bug.cgi?id=1332447

**Comment by leedoyle** [comment]
@Keith94 I know it's not feasible w/ WE yet, but Vertical Tabs Reloaded does that as it's a hybrid extension. And more importantly, the original Tab Center has been doing that, too.

**Comment by asampal** [comment]
@Croydon , thanks for the dev release. Is the problem of not being able to drag-and-drop tabs known to be an issue with this version and Firefox 54?

**Comment by Croydon** [comment]
@asampel The dev version only supports FF55+ official. Also it depends which sidebar you are using, the WebExtensions sidebar has no drag&drop implementation yet, but I'm guessing you are using the legacy one and there it should work. What other add-ons are you using?

**Comment by asampal** [comment]
@Croydon , I'm also using Tab Mix Plus - the other add-ons aren't tab related, so I don't think they should cause problems.

**Comment by asampal** [comment]
I'm not sure what caused the drag-and-drop problem, but after a restart of browser (which I had done before), this now works with VTR 0.8.4-alpha and FF 54.

**Comment by grahamperrin** [comment]
0.8.4-alpha works for me with 55.0b9 (32-bit) on Kubuntu. 

Tested: 

- drag from initial window
- drop on second window. 

I'll test later with 54.0.1 (64-bit) on KDE Plasma 5 on FreeBSD-CURRENT.

**Comment by grahamperrin** [comment]
[RapidRelease/Calendar - MozillaWiki](https://wiki.mozilla.org/RapidRelease/Calendar) – with 55 scheduled for release Tuesday 2017-08-08 (three days from now), might it be sensible to make 0.8.4 available as an update on Monday? 

### 0.8.4-alpha with Firefox 54.0.1 (64-bit) on KDE Plasma 5 on FreeBSD-CURRENT

Tested over a three-week period. Drag-and-drop across windows, across multiple desktops, is OK. 

> tabs remain visible in fullscreen

+1

**Comment by Croydon** [comment]
@grahamperrin This was the original plan all the way, have a look at the very beginning of #13 for a timetable :)

**Comment by grahamperrin** [comment]
My bad! https://github.com/Croydon/vertical-tabs-reloaded/issues/99#issuecomment-308137779 makes it clear. Thanks.

**Comment by Croydon** [comment]
v0.8.4 is now in the review queue. I will close this issue, when the version is public.

**Comment by Croydon** [comment]
Published.
